<?php
session_start();require_once __DIR__.'/db_connect.php';require_once __DIR__.'/includes/require_role.php';require_login();require_role(['Admin'],'My Drafts');
require_once __DIR__.'/includes/accounting_workspace.php';require_once __DIR__.'/includes/layout.php';
try{workspace_guard($pdo,(int)$_SESSION['UserID']);}catch(JournalProblem $e){http_response_code($e->status);exit(htmlspecialchars($e->getMessage(),ENT_QUOTES,'UTF-8'));}
layout_begin('My Drafts','general_journal',[], '<link rel="stylesheet" href="assets/css/accounting_workspace.css?v='.filemtime(__DIR__.'/assets/css/accounting_workspace.css').'">');
?>
<div class="accounting-workspace"><header class="aw-header"><div><p class="aw-eyebrow">DAILY ACCOUNTING</p><h1>My drafts</h1><p>Private saved work. Drafts have no effect on financial records.</p></div><div><a href="cash_receipt.php">New receipt</a> · <a href="cash_disbursement.php">New payment</a> · <a href="general_journal.php">New journal</a></div></header>
<section class="aw-card"><form id="draft-filters" class="aw-draft-filters"><label>Entry type<select name="source_book"><option value="">All types</option><option>CRB</option><option>CDB</option><option>GJ</option></select></label><label>Last saved from<input name="from" type="date" min="1000-01-01" max="9998-12-31"></label><label>Last saved to<input name="to" type="date" min="1000-01-01" max="9998-12-31"></label><button>Apply filters</button></form><p class="aw-help">Date filters use the last saved date in Asia/Manila. The accounting date remains shown for each draft.</p><p role="status" id="draft-filter-status"></p><p role="status" id="draft-status"></p><p role="alert" id="draft-error"></p><div class="aw-table-wrap"><table class="aw-table"><thead><tr><th>Draft</th><th>Type / accounting date</th><th>Purpose</th><th>Last saved (Asia/Manila)</th><th>Actions</th></tr></thead><tbody id="draft-list"></tbody></table></div></section></div>
<script type="application/json" id="draft-data"><?= json_encode(['csrf_token'=>csrf_token()],JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT) ?></script>
<?php layout_end('<script src="assets/js/accounting_drafts.js?v='.filemtime(__DIR__.'/assets/js/accounting_drafts.js').'"></script>'); ?>
