<?php
session_start();require_once __DIR__.'/db_connect.php';require_once __DIR__.'/includes/require_role.php';require_login();require_role(['Admin','Management'],'Cash advances');require_once __DIR__.'/includes/cash_advance.php';require_once __DIR__.'/includes/layout.php';
if($_SERVER['REQUEST_METHOD']!=='GET'){header('Allow: GET');http_response_code(405);exit;}
header('Cache-Control: private, no-store');
try{$uid=(int)$_SESSION['UserID'];$role=advance_guard($pdo,$uid);$id=journal_id(journal_string($_GET,'advance_id',true),true);$asof=advance_date(journal_string($_GET,'as_of',true)?:journal_today());
    $options=accounting_read($pdo,fn()=>array_map('advance_summary',array_values(advance_state($pdo,journal_today())['advances'])));
    $detail=$id===null?null:advance_detail($pdo,$uid,$id,$asof);
}catch(JournalProblem $e){http_response_code($e->status);exit(htmlspecialchars($e->getMessage(),ENT_QUOTES,'UTF-8'));}
$esc=fn($v)=>htmlspecialchars((string)$v,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');
layout_begin('Cash advances','cash_advances',[],'<link rel="stylesheet" href="assets/css/accounting_workspace.css?v='.filemtime(__DIR__.'/assets/css/accounting_workspace.css').'">');
?>
<div class="accounting-workspace advance-register" id="advance-register">
<header class="aw-header"><div><p class="aw-eyebrow">CASH ADVANCES</p><h1><?= $detail?$esc($detail['number']):'Cash advance register' ?></h1><p>Track released funds, supported liquidations and returned cash.</p></div><div class="aw-no-print"><a href="cash_advances.php">Register</a><?php if($role==='Admin'): ?> · <a href="cash_advance_entry.php?workflow_kind=advance_release">Release an advance</a> · <a href="accounting_drafts.php">My drafts</a><?php endif; ?> · <button type="button" id="ca-print">Print</button></div></header>
<p id="ca-error" role="alert" tabindex="-1"></p><p id="ca-status" role="status"></p>
<?php if($detail): ?>
<p>POSTED advance · As of <?= $esc($asof) ?> · Historical views include currently recorded postings through this accounting date.</p>
<form method="get" class="aw-no-print aw-actions"><input type="hidden" name="advance_id" value="<?= $id ?>"><label>As of<input type="date" name="as_of" value="<?= $esc($asof) ?>" max="<?= journal_today() ?>" min="1000-01-01"></label><button>Apply date</button></form>
<section class="aw-card"><h2><?= $esc($detail['employee']) ?></h2><p><?= $esc($detail['purpose']) ?></p><p>Reference: <?= $esc($detail['reference']?:'None') ?> · Originating project: <?= $esc($detail['project']) ?></p><div class="aw-totals"><?php foreach(['released','liquidated','returned','outstanding'] as $k): ?><span><?= ucfirst($k) ?><strong>PHP <?= $esc($detail[$k]) ?></strong></span><?php endforeach; ?></div><p><?= $esc(str_replace('_',' ',$detail['status'])) ?> · Due <?= $esc($detail['due_date']) ?> · <?= $detail['overdue_days'] ?> days overdue · <?= $esc($detail['aging_bucket']) ?></p>
<?php if($detail['can_settle']): ?><div class="aw-actions aw-no-print"><a href="cash_advance_entry.php?workflow_kind=advance_liquidation&amp;advance_id=<?= $id ?>">Liquidate</a><a href="cash_advance_entry.php?workflow_kind=advance_return&amp;advance_id=<?= $id ?>">Return unused cash</a></div><form id="ca-extension" class="aw-grid aw-no-print"><label>New liquidation due date<input name="due_date" type="date" min="<?= journal_today() ?>" required></label><label>Reason for extension<textarea name="reason" required maxlength="2000"></textarea></label><button>Extend deadline</button></form><?php endif; ?>
<?php if($role==='Admin'&&$detail['external_approval']): ?><p>External approval recorded by accounting staff: <?= $esc($detail['external_approval']['name']) ?> · <?= $esc($detail['external_approval']['date']) ?> · <?= $esc($detail['external_approval']['reference']) ?></p><?php endif; ?></section>
<section class="aw-card"><h2>Posted operation timeline</h2><?php foreach($detail['operations'] as $op): ?><article class="ca-operation"><h3><?= ucfirst($op['kind']) ?> · <?= $esc($op['date']) ?> · Journal #<?= $op['journal_id'] ?></h3><p>Advance <?= $op['kind']==='release'?'release':'reduction' ?>: PHP <?= $esc($op['amount']) ?> · <?= $esc($op['coverage']['status']) ?></p><p>Recorded <?= $esc($op['recorded_at_display']) ?> (Asia/Manila) · Reference <?= $esc($op['reference']?:'None') ?></p><div class="aw-table-wrap"><table class="aw-table"><thead><tr><th>Account</th><th>Project</th><th>Debit (PHP)</th><th>Credit (PHP)</th></tr></thead><tbody><?php foreach($op['lines'] as $l): ?><tr><td><?= $esc($l['account_name']) ?></td><td><?= $esc($l['project_name_snapshot']??'Organization operations') ?></td><td><?= $esc($l['debit_amount']) ?></td><td><?= $esc($l['credit_amount']) ?></td></tr><?php endforeach; ?></tbody></table></div><?php if($role==='Admin'): foreach($op['attachments'] as $doc): ?><p class="aw-no-print"><a href="<?= $esc($doc['url']) ?>" target="_blank" rel="noopener"><?= $esc($doc['name']) ?></a></p><?php endforeach; endif; ?></article><?php endforeach; ?></section>
<section class="aw-card"><h2>Deadline history</h2><p>Initial deadline: <?= $esc($detail['initial_due_date']) ?></p><?php foreach($detail['due_changes'] as $change): ?><p><?= $esc($change['effective_date']) ?>: <?= $esc($change['old_due_date']) ?> → <?= $esc($change['new_due_date']) ?> · <?= $esc($change['reason']) ?></p><?php endforeach; ?></section>
<?php else: ?>
<form id="ca-filters" class="aw-card aw-no-print"><div class="aw-grid"><label>As of<input name="as_of" type="date" value="<?= $esc($asof) ?>" max="<?= journal_today() ?>" min="1000-01-01" required></label>
<?php foreach(['party_id'=>'Employee','project_id'=>'Originating project','control_account_id'=>'Control account'] as $field=>$label): ?><label><?= $label ?><select name="<?= $field ?>"><option value="">All</option><?php if($field==='project_id'): ?><option value="organization">Organization operations</option><?php endif; $seen=[];foreach($options as $row){$value=$row[$field==='project_id'?'originating_project_id':$field];if($value===null||isset($seen[$value]))continue;$seen[$value]=true;$text=$field==='party_id'?$row['employee']:($field==='project_id'?$row['project']:'Account #'.$value); ?><option value="<?= $value ?>"><?= $esc($text) ?></option><?php } ?></select></label><?php endforeach; ?>
<label>Settlement status<select name="status"><option value="">All</option><option value="outstanding">Outstanding</option><option value="partially_settled">Partially settled</option><option value="settled">Settled</option></select></label><label>Overdue<select name="overdue"><option value="">All</option><option value="1">Overdue</option><option value="0">Not overdue</option></select></label><label>Search number, employee, purpose or reference<input name="search" maxlength="200" type="search"></label></div><div class="aw-actions"><span id="ca-filter-status" role="status"></span><button class="aw-primary">Apply filters</button></div></form>
<section class="aw-card"><h2 id="ca-basis">Posted advances</h2><p id="ca-notice"></p><div class="aw-totals" id="ca-totals"></div><div class="aw-table-wrap"><table class="aw-table"><thead><tr><th>Advance / employee</th><th>Release / project</th><th>Released (PHP)</th><th>Liquidated (PHP)</th><th>Returned (PHP)</th><th>Outstanding (PHP)</th><th>Deadline / status</th></tr></thead><tbody id="ca-rows"></tbody></table></div><div class="aw-actions aw-no-print"><button type="button" id="ca-prev">Previous</button><span id="ca-page"></span><button type="button" id="ca-next">Next</button></div></section>
<?php endif; ?>
<section class="aw-card"><h2>Full control-account reconciliation — independent of register filters</h2><p>All posted advances and control-account lines through the same accounting date are included.</p><div id="ca-reconciliation"></div></section>
</div>
<script type="application/json" id="advance-data"><?= json_encode(['csrf_token'=>csrf_token(),'detail'=>$detail],JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT|JSON_THROW_ON_ERROR) ?></script>
<?php layout_end('<script src="assets/js/cash_advances.js?v='.filemtime(__DIR__.'/assets/js/cash_advances.js').'"></script>'); ?>
