<?php
/** New disposable database only; run prior suites, then exercise financially inert v4 drafts. */
require __DIR__.'/test_stage3_checkpoint1.php';
require_once __DIR__.'/../includes/correction_drafts.php';
define('STAGE3_CORRECTIONS_ENABLED',true);
$regression=$prior+['stage3_checkpoint1'=>$checks];$checks=0;
function cdsave(PDO $p,int $uid,array $t,string $mode='reverse_replace',?array $payload=null,?array $draft=null,string $book=''): array
{
    $book=correction_book($t,$mode,$book?:($t['journal']['source_book']?:'GJ'));
    return correction_save($p,$uid,request(($draft?identity($draft):['draft_id'=>'','submission_key'=>bin2hex(random_bytes(32))])+['target_journal_id'=>(string)$t['journal']['id'],'mode'=>$mode,'source_book'=>$book,'payload'=>$payload??correction_seed($t,$mode,$book)]));
}
function cdupdate(PDO $p,int $uid,array $d,array $payload): array {return cdsave($p,$uid,correction_target($p,(int)$d['correction_target_journal_id']),$d['correction_mode'],$payload,$d,$d['source_book']);}
try{
    $_SESSION=['UserID'=>$uid,'Role'=>'Admin'];
    // A new synthetic payment is fixture setup, not a correction-draft financial write.
    $fixtureDraft=save($p,$uid,'CDB',payload([line('fixture_cost',$training,'1000.00')],(int)$party['id'],$bank,'1000.00'));$fixtureImage=stage_image($p,$uid);$fixtureDraft=workspace_attach($p,$uid,request(identity($fixtureDraft)),$fixtureImage);$fixturePayload=$fixtureDraft['payload'];$fixturePayload['documents'][0]=['receipt_id'=>(string)$fixtureImage,'reviewed'=>true,'purpose'=>'amount','support_side'=>'debit','declared_amount'=>'1000.00','accepted_amount'=>'1000.00','exclusion_reason'=>'','allocations'=>[['client_id'=>'fixture_cost','amount'=>'1000.00']]];$fixtureDraft=workspace_save($p,$uid,request(identity($fixtureDraft)+['source_book'=>'CDB','payload'=>$fixturePayload]));$fixturePayment=workspace_post($p,$uid,post_request($p,$uid,$fixtureDraft));
    $initial=$p->query("SELECT id FROM journal_entries WHERE source_book='CDB' AND transaction_kind='ordinary' AND id NOT IN(SELECT target_journal_id FROM journal_corrections) ORDER BY id LIMIT 1")->fetchColumn();$t=correction_target($p,(int)$initial);$financial=s3manifest($p);$financial=array_intersect_key($financial,array_flip(['journal_entries','journal_entry_lines','cash_advances','cash_advance_operations','posted_evidence_associations','evidence_allocations']));
    $d=cdsave($p,$uid,$t);st((int)$d['payload_version']===4&&$d['workflow_kind']==='correction'&&$d['payload']['replacement']['documents']===[],'Owned v4 draft copies financial fields without copying reviews');
    $creation=request(['draft_id'=>'','submission_key'=>$d['submission_key'],'target_journal_id'=>(string)$initial,'mode'=>'reverse_replace','source_book'=>$d['source_book'],'payload'=>$d['payload']]);st(correction_save($p,$uid,$creation)['id']===$d['id'],'Matching lost creation response recovers original v4 draft');
    $bad=$creation;$bad['payload']['reason']='changed';no($p,fn()=>correction_save($p,$uid,$bad),'Changed durable creation payload',409);
    $_SESSION=['UserID'=>(int)$users['other@example.invalid'],'Role'=>'Admin'];no($p,fn()=>correction_draft($p,(int)$_SESSION['UserID'],(int)$d['id']),'Other Admin cannot load private correction draft',404);$_SESSION=['UserID'=>$uid,'Role'=>'Admin'];
    foreach(['ordinary'=>'workspace_review','advance'=>'advance_review'] as $label=>$fn)no($p,fn()=>$fn($p,$uid,request(identity($d))),$label.' review rejects v4',409);
    no($p,fn()=>workspace_upload($p,$uid,request(identity($d)+['upload_key'=>bin2hex(random_bytes(32))]),[]),'Old upload rejects v4 before storing bytes',409);
    no($p,fn()=>workspace_remove_or_discard($p,$uid,request(identity($d)),true),'Old discard rejects v4',409);
    $payload=$d['payload'];$payload['reason']='Correct amount in dummy demonstration';$d=cdupdate($p,$uid,$d,$payload);$rev=correction_review($p,$uid,request(identity($d)));st($rev['posting_available']&&$rev['reversal']['source_book']==='GJ'&&count($rev['reversal']['lines'])===count($t['lines']),'Review compares full generated reversal and replacement without writing');
    $stale=$d;$d=cdupdate($p,$uid,$d,$d['payload']);no($p,fn()=>cdupdate($p,$uid,$stale,$stale['payload']),'Stale revision',409);
    $wrong=request(identity($d)+['target_journal_id'=>(string)$initial,'mode'=>'reverse_only','source_book'=>'GJ','payload'=>['entry_date'=>journal_today(),'reason'=>'Duplicate','backdate_reason'=>'','replacement'=>null]]);no($p,fn()=>correction_save($p,$uid,$wrong),'Mode is immutable',409);
    $payload=$d['payload'];$payload['entry_date']='9998-01-01';$future=cdupdate($p,$uid,$d,$payload);no($p,fn()=>correction_review($p,$uid,request(identity($future))),'Future correction date',400);
    $payload['entry_date']=$t['journal']['entry_date'];$d=cdupdate($p,$uid,$future,$payload);
    $originalImage=(int)$p->query('SELECT receipt_id FROM posted_evidence_associations WHERE journal_id='.$initial.' LIMIT 1')->fetchColumn();
    st($originalImage>0,'Synthetic payment has original posted evidence');
    $d=correction_attach($p,$uid,request(identity($d)+['receipt_id'=>(string)$originalImage]),true);$public=correction_public($p,$uid,correction_draft($p,$uid,(int)$d['id']));
    st($public['document_details'][0]['reused']&&!$d['payload']['replacement']['documents'][0]['reviewed'],'Reuse reserves exact target association and requires fresh review');
    st(correction_draft_download_allowed($p,$uid,(int)$d['id'],$originalImage),'Owner can preview the reserved posted image');
    no($p,fn()=>correction_review($p,$uid,request(identity($d))),'Unreviewed reused image');
    $_SESSION=['UserID'=>(int)$users['other@example.invalid'],'Role'=>'Admin'];$otherUid=(int)$_SESSION['UserID'];$other=cdsave($p,$otherUid,$t);no($p,fn()=>correction_attach($p,$otherUid,request(identity($other)+['receipt_id'=>(string)$originalImage]),true),'Other Admin cannot steal reuse reservation',409);st(!correction_draft_download_allowed($p,$otherUid,(int)$d['id'],$originalImage),'Guessed draft download denied');
    $_SESSION=['UserID'=>$uid,'Role'=>'Admin'];
    $payload=$d['payload'];$doc=&$payload['replacement']['documents'][0];$doc['reviewed']=true;$d=cdupdate($p,$uid,$d,$payload);no($p,fn()=>correction_review($p,$uid,request(identity($d))),'Changed reused purpose requires re-review reason');
    $payload=$d['payload'];$payload['replacement']['documents'][0]['re_review_reason']='Using original document as informational reference';$d=cdupdate($p,$uid,$d,$payload);st(correction_review($p,$uid,request(identity($d)))['coverage']['status']==='No monetary support','Informational reused proof does not invent monetary coverage');
    $privateImage=stage_image($p,$uid);$d=correction_attach($p,$uid,request(identity($d)+['receipt_id'=>(string)$privateImage]));st(count(correction_documents($d))===2,'New evidence and reused evidence coexist with separate reservations');
    $released=correction_remove_or_discard($p,$uid,request(identity($d)+['receipt_id'=>(string)$originalImage]),false);st((int)$p->query('SELECT COUNT(*) FROM correction_evidence_reservations WHERE receipt_id='.$originalImage)->fetchColumn()===0&&$p->query('SELECT Posted_File_SHA256 FROM Receipts WHERE ReceiptID='.$originalImage)->fetchColumn()!==null,'Removal releases reuse reservation without changing posted image');
    $d=correction_attach($p,$uid,request(identity($released)+['receipt_id'=>(string)$originalImage]),true);
    $unchanged=array_intersect_key(s3manifest($p),$financial);st($unchanged===$financial,'Draft save, review, attach and remove preserve every financial/evidence posting hash');
    $staleUi=cdsave($p,$uid,$t);
    // A successful winner invalidates the competitor, but a rolled-back winner must restore its reservation.
    $p->beginTransaction();$winner=s3fixture($p,$otherUid,(int)$initial,false);st(correction_release_stale_reservations($p,$winner['draft'])===1,'Winning correction releases only exact-target reused reservation');$p->rollBack();st((int)$p->query('SELECT draft_id FROM correction_evidence_reservations WHERE receipt_id='.$originalImage)->fetchColumn()===(int)$d['id'],'Rollback restores stale reservation cleanup');
    $unrelatedTarget=(int)$fixturePayment['id'];$unusedUnrelatedTarget=(int)$p->query("SELECT j.id FROM journal_entries j JOIN posted_evidence_associations a ON a.journal_id=j.id WHERE j.id<>".$initial." AND j.transaction_kind='ordinary' AND NOT EXISTS(SELECT 1 FROM journal_corrections c WHERE c.target_journal_id=j.id) LIMIT 1")->fetchColumn();$unrelated=cdsave($p,$uid,correction_target($p,$unrelatedTarget));$unrelatedReceipt=(int)$p->query('SELECT receipt_id FROM posted_evidence_associations WHERE journal_id='.$unrelatedTarget.' LIMIT 1')->fetchColumn();$unrelated=correction_attach($p,$uid,request(identity($unrelated)+['receipt_id'=>(string)$unrelatedReceipt]),true);
    $p->beginTransaction();$winner=s3fixture($p,$otherUid,(int)$initial,false);correction_release_stale_reservations($p,$winner['draft']);$p->commit();$stalePublic=correction_public($p,$uid,correction_draft($p,$uid,(int)$d['id']));
    st(!$stalePublic['target']['eligible']&&str_contains($stalePublic['target']['ineligible_reason'],'already been corrected')&&count(correction_documents($d))===2,'Stale draft and entered values remain, with corrected-target explanation');
    st((int)$p->query('SELECT COUNT(*) FROM draft_evidence_reservations WHERE receipt_id='.$privateImage)->fetchColumn()===1&&(int)$p->query('SELECT COUNT(*) FROM correction_evidence_reservations WHERE receipt_id='.$unrelatedReceipt)->fetchColumn()===1,'Cleanup preserves private upload and unrelated valid reuse reservation');
    no($p,fn()=>correction_review($p,$uid,request(identity($d))),'Stale review rejects a corrected target',409);
    $d=correction_remove_or_discard($p,$uid,request(identity($d)+['receipt_id'=>(string)$originalImage]),false);$d=correction_remove_or_discard($p,$uid,request(identity($d)),true);st($d['state']==='Discarded'&&is_file(receipt_file_verify($p->query('SELECT * FROM Receipts WHERE ReceiptID='.$originalImage)->fetch())),'Stale discard tolerates deliberate release and preserves posted bytes');
    $p->exec('DELETE FROM correction_evidence_reservations WHERE receipt_id='.$unrelatedReceipt);no($p,fn()=>correction_remove_or_discard($p,$uid,request(identity($unrelated)),true),'Unexplained missing reservation is not hidden',409);$source=correction_source($p,$unrelated,$unrelatedReceipt);$p->prepare('INSERT INTO correction_evidence_reservations VALUES(?,?,?,UTC_TIMESTAMP())')->execute([$unrelatedReceipt,$unrelated['id'],$source['id']]);correction_remove_or_discard($p,$uid,request(identity($unrelated)),true);
    // Valid replacement liquidation reuses the immediate target association, excluding control credit.
    $liqTarget=correction_target($p,(int)$last['replacement']);$liqDraft=cdsave($p,$uid,$liqTarget);$payload=$liqDraft['payload'];$payload['reason']='Synthetic liquidation amount correction';foreach($payload['replacement']['lines'] as $l)if(journal_amount($l['credit_amount'])>0)$payload['replacement']['line_notes'][$l['client_id']]='Reviewed withholding allocation from target';$liqDraft=cdupdate($p,$uid,$liqDraft,$payload);$liqImage=(int)$p->query('SELECT receipt_id FROM posted_evidence_associations WHERE journal_id='.$last['replacement'].' LIMIT 1')->fetchColumn();$liqDraft=correction_attach($p,$uid,request(identity($liqDraft)+['receipt_id'=>(string)$liqImage]),true);$payload=$liqDraft['payload'];$gross=array_sum(array_map(fn($l)=>journal_amount($l['debit_amount']),$payload['replacement']['lines']));$payload['replacement']['documents'][0]=['receipt_id'=>(string)$liqImage,'reviewed'=>true,'purpose'=>'amount','support_side'=>'debit','declared_amount'=>ledger_decimal($gross),'accepted_amount'=>ledger_decimal($gross),'exclusion_reason'=>'','re_review_reason'=>'Fresh review for linked replacement','allocations'=>array_values(array_map(fn($l)=>['client_id'=>$l['client_id'],'amount'=>$l['debit_amount']],array_filter($payload['replacement']['lines'],fn($l)=>journal_amount($l['debit_amount'])>0)))];$liqDraft=cdupdate($p,$uid,$liqDraft,$payload);$review=correction_review($p,$uid,request(identity($liqDraft)));st($review['coverage']['debit']['eligible']===ledger_decimal($gross)&&$review['coverage']['credit']['eligible']==='0.00','Replacement liquidation supports gross costs once, not the control credit');
    $returnOperation=$p->query("SELECT o.* FROM cash_advance_operations o WHERE o.operation_kind='return' AND NOT EXISTS(SELECT 1 FROM journal_corrections c WHERE c.target_journal_id=o.journal_id) LIMIT 1")->fetch();
    $returnPost=['id'=>$returnOperation['journal_id']];$released=['advance_id'=>$returnOperation['advance_id'],'id'=>$p->query('SELECT release_journal_id FROM cash_advances WHERE id='.(int)$returnOperation['advance_id'])->fetchColumn()];
    $proof=(int)$p->query('SELECT receipt_id FROM posted_evidence_associations WHERE journal_id='.(int)$returnPost['id'].' LIMIT 1')->fetchColumn();
    $returnTarget=correction_target($p,(int)$returnPost['id']);$rd=cdsave($p,$uid,$returnTarget);$payload=$rd['payload'];$payload['reason']='Correct returned amount';$payload['replacement']['cash_amount']='15.00';$rd=cdupdate($p,$uid,$rd,$payload);$rd=correction_attach($p,$uid,request(identity($rd)+['receipt_id'=>(string)$proof]),true);$payload=$rd['payload'];$payload['replacement']['documents'][0]['reviewed']=true;$rd=cdupdate($p,$uid,$rd,$payload);no($p,fn()=>correction_review($p,$uid,request(identity($rd))),'Return replacement requires fresh confirmation',409);$rd=correction_confirm($p,$uid,request(identity($rd)));$review=correction_review($p,$uid,request(identity($rd)));st($review['coverage']['status']==='Return proof confirmed','Return confirmation binds correction target, original advance, amount and proof');
    $payload=$rd['payload'];$payload['replacement']['cash_amount']='16.00';$rd=cdupdate($p,$uid,$rd,$payload);st($rd['return_confirmation']===null,'Changed return amount invalidates confirmation');no($p,fn()=>correction_review($p,$uid,request(identity($rd))),'Changed amount requires reconfirmation',409);
    $releaseTarget=correction_target($p,(int)$released['id']);st(!$releaseTarget['eligible']&&count($releaseTarget['blockers'])>=1,'Release with effective return shows exact blocking operation');
    // New releases never inherit inactive-reference exceptions.
    $releaseOperation=$p->query("SELECT o.* FROM cash_advance_operations o WHERE o.operation_kind='release' AND NOT EXISTS(SELECT 1 FROM cash_advance_operations settlement WHERE settlement.advance_id=o.advance_id AND settlement.operation_kind<>'release') AND NOT EXISTS(SELECT 1 FROM journal_corrections c WHERE c.target_journal_id=o.journal_id) LIMIT 1")->fetch();
    $fresh=['id'=>$releaseOperation['journal_id']];$releaseTarget=correction_target($p,(int)$fresh['id']);$newRelease=cdsave($p,$uid,$releaseTarget);$payload=$newRelease['payload'];$payload['reason']='New release identity';$newRelease=cdupdate($p,$uid,$newRelease,$payload);$p->exec('UPDATE parties SET is_active=0 WHERE id='.(int)$employee['id']);no($p,fn()=>correction_review($p,$uid,request(identity($newRelease))),'Replacement release cannot retain inactive employee');$p->exec('UPDATE parties SET is_active=1 WHERE id='.(int)$employee['id']);
    $only=cdsave($p,$uid,correction_target($p,(int)$fresh['id']),'reverse_only');$payload=$only['payload'];$payload['reason']='Duplicate synthetic entry';$only=cdupdate($p,$uid,$only,$payload);st(correction_review($p,$uid,request(identity($only)))['lines']===[],'Reversal-only preview has no replacement or evidence claim');
    $draftRows=workspace_drafts($p,$uid,['source_book'=>'','from'=>'','to'=>'']);st(count(array_filter($draftRows,fn($row)=>$row['workflow_kind']==='correction'&&$row['correction_target_journal_id']!==null))>0,'My Drafts includes correction identity and nested description');
    $_SESSION=['UserID'=>(int)$users['management@example.invalid'],'Role'=>'Admin'];no($p,fn()=>correction_guard($p,(int)$_SESSION['UserID']),'Database Management role cannot read correction drafts',403);$_SESSION=['UserID'=>$uid,'Role'=>'Admin'];
    st(correction_integrity($p)===[],'Final draft/reservation/correction integrity is valid');
    file_put_contents($run.'/stage3-checkpoint2-fixture.json',workspace_json(['database'=>$db,'receipt_root'=>RECEIPT_UPLOAD_DIR,'payment_target'=>$unrelatedTarget,'liquidation_target'=>$last['replacement'],'return_target'=>$returnPost['id'],'release_target'=>$fresh['id'],'stale_draft'=>$staleUi['id'],'posted_draft'=>$winner['draft'],'liquidation_draft'=>$liqDraft['id'],'return_draft'=>$rd['id'],'bank'=>$bank,'training'=>$training,'employee'=>$employee['id'],'control'=>$ctrl]));
    echo "Stage 3 checkpoint 2 checks: $checks\nStage 3 checkpoint 2 fixture: $run/stage3-checkpoint2-fixture.json\n";
}catch(Throwable $e){if($p->inTransaction())$p->rollBack();fwrite(STDERR,$e->getMessage()."\n".$e->getTraceAsString()."\n");exit(1);}
