<?php
/** Creates a new guarded synthetic database; never loads working configuration. */
require_once __DIR__.'/cli_common.php';
$opt=getopt('',['database:','worker:']);$testDb=$opt['database']??'';
cli_require(is_string($testDb)&&(bool)preg_match('/\Aatikha_test_stage1_[a-z0-9]+\z/',$testDb),'A NEW atikha_test_stage1_* database is required (shared Stage 1 bootstrap).');
define('STAGE2_ADVANCES_ENABLED',true);
if(isset($opt['worker'])){
    define('ATIKHA_ISOLATED_TEST',true);
    $base=realpath(__DIR__.'/../.migration-private');$path=realpath($opt['worker']);cli_require($path&&$base&&str_starts_with($path,$base.DIRECTORY_SEPARATOR),'Private worker fixture required.');$f=json_decode(file_get_contents($path),true);
    $evidence=realpath($f['receipt_root']);cli_require($evidence&&str_starts_with($evidence,$base.DIRECTORY_SEPARATOR),'Private evidence required.');
    define('RECEIPT_UPLOAD_DIR',$evidence);define('STAGE1_WORKSPACE_ENABLED',true);define('OCR_JOURNAL_ENABLED',false);require_once __DIR__.'/../includes/cash_advance.php';$_SESSION=$f['session'];
    try{$out=advance_post(cli_db($testDb),(int)$_SESSION['UserID'],$f['post']);echo workspace_json(['ok'=>true,'result'=>$out]);}catch(Throwable $e){echo workspace_json(['ok'=>false,'error'=>$e->getMessage()]);}exit;
}
require __DIR__.'/test_stage1.php';
require_once __DIR__.'/../includes/cash_advance.php';
$stage1Checks=$checks;$checks=0;
function avsave(PDO $p,int $uid,string $kind,array $payload,?int $target=null,?array $draft=null): array
{
    return advance_save($p,$uid,request(($draft?identity($draft):['draft_id'=>'','submission_key'=>bin2hex(random_bytes(32))])+['workflow_kind'=>'advance_'.$kind,'advance_id'=>$target===null?'':(string)$target,'payload'=>$payload]));
}
function avpostrequest(PDO $p,int $uid,array $d): array {$v=advance_review($p,$uid,request(identity($d)));return request(identity($d)+['payload'=>$d['payload'],'review_token'=>$v['token']]);}
function avsupport(PDO $p,int $uid,array $d,?string $amount=null,string $client='cost'): array
{
    $d=workspace_attach($p,$uid,request(identity($d)),stage_image($p,$uid));$payload=$d['payload'];$doc=&$payload['documents'][count($payload['documents'])-1];$doc['reviewed']=true;
    if($amount!==null){$doc['purpose']='amount';$doc['support_side']='debit';$doc['declared_amount']=$doc['accepted_amount']=$amount;$doc['allocations']=[['client_id'=>$client,'amount'=>$amount]];}unset($doc);
    return avsave($p,$uid,substr($d['workflow_kind'],8),$payload,$d['workflow_kind']==='advance_release'?null:(int)$d['advance_id'],$d);
}
function avrelease(PDO $p,int $uid,int $employee,int $bank,int $ctrl,string $amount,?string $date=null,?string $due=null,?int $project=null): array
{
    $payload=payload([],$employee,$bank,$amount);$payload['entry_date']=$date??journal_today();$payload['due_date']=$due??journal_today();$payload['control_account_id']=(string)$ctrl;$payload['default_project_id']=$project===null?'':(string)$project;
    $d=avsave($p,$uid,'release',$payload);$post=avpostrequest($p,$uid,$d);return advance_post($p,$uid,$post)+['draft'=>$d,'post'=>$post];
}
function avcount(PDO $p): array {return counts($p)+[3=>(int)$p->query('SELECT COUNT(*) FROM cash_advances')->fetchColumn(),4=>(int)$p->query('SELECT COUNT(*) FROM cash_advance_operations')->fetchColumn(),5=>(int)$p->query('SELECT COUNT(*) FROM posted_evidence_associations')->fetchColumn()];}
try{
    $before=counts($p);$hashes=$p->query('SELECT id,submission_hash FROM journal_entries ORDER BY id')->fetchAll();cli_sql_file($p,__DIR__.'/../migrations/020_stage2_advances.sql');
    st(stage2_enabled($p)&&counts($p)===$before&&$hashes===$p->query('SELECT id,submission_hash FROM journal_entries ORDER BY id')->fetchAll(),'020 adds schema without changing journals, hashes or evidence');
    $ctrl=(int)$advance;$employee=workspace_master_save($p,$uid,request(['kind'=>'parties','name'=>'Synthetic NGO field coordinator','party_type'=>'person','reference'=>'','description'=>'Dummy NGO staff','is_active'=>'1']));$employee2=workspace_master_save($p,$uid,request(['kind'=>'parties','name'=>'Synthetic NGO trainer','party_type'=>'person','reference'=>'','description'=>'Dummy NGO staff','is_active'=>'1']));
    $pr=workspace_master_save($p,$uid,request(['kind'=>'projects','name'=>'Synthetic financial literacy outreach','code'=>'DEMO-S2','description'=>'Dummy NGO project','is_active'=>'1']));
    $released=avrelease($p,$uid,(int)$employee['id'],$bank,$ctrl,'10000.00',null,null,(int)$pr['id']);$aid=$released['advance_id'];
    st(advance_register($p,$uid,[])['totals']['outstanding']==='10000.00','Release creates a posted asset balance and permanent advance number');
    st($p->query('SELECT transaction_kind FROM journal_entries WHERE id='.$released['id'])->fetchColumn()==='advance_release','Release routes to CDB with server workflow kind');
    $c=avcount($p);$_SESSION=['UserID'=>$uid,'Role'=>'Admin'];$retry=$released['post'];$retry['csrf_token']=csrf_token();$retry['review_token']='1000000000.'.str_repeat('0',64);st(advance_post($p,$uid,$retry)['duplicate']&&avcount($p)===$c,'Release retry after login and expired token recovers one operation');
    $bad=$retry;$bad['payload']['cash_amount']='9999.00';no($p,fn()=>advance_post($p,$uid,$bad),'Changed successful advance retry',409);
    $saved=workspace_draft($p,$uid,(int)$released['draft']['id']);no($p,fn()=>workspace_post($p,$uid,$retry),'Ordinary posting cannot accept a v3 draft',409);no($p,fn()=>workspace_ordinary($saved),'Ordinary document route rejects advance context',409);
    $liq=avsave($p,$uid,'liquidation',payload([line('cost',$training,'8000.00','',(int)$pr['id'])]),$aid);no($p,fn()=>advance_review($p,$uid,request(identity($liq))),'Unsupported liquidation');
    $liq=avsupport($p,$uid,$liq,'8000.00');$review=advance_review($p,$uid,request(identity($liq)));st($review['coverage']['debit']===['eligible'=>'8000.00','covered'=>'8000.00']&&$review['coverage']['credit']['eligible']==='0.00','Liquidation coverage excludes the control credit');
    $lpost=advance_post($p,$uid,avpostrequest($p,$uid,$liq));st(advance_detail($p,$uid,$aid,journal_today())['outstanding']==='2000.00','8000 supported liquidation reduces 10000 advance to 2000');
    $ret=avsave($p,$uid,'return',payload([],0,$petty,'2000.00'),$aid);no($p,fn()=>advance_review($p,$uid,request(identity($ret))),'Return without proof');$ret=avsupport($p,$uid,$ret);no($p,fn()=>advance_review($p,$uid,request(identity($ret))),'Return without explicit bound confirmation',409);
    $ret=advance_confirm($p,$uid,request(identity($ret)));$rp=$ret['payload'];$rp['cash_amount']='1500.00';$changed=avsave($p,$uid,'return',$rp,$aid,$ret);st($changed['return_confirmation']===null,'Changing a confirmed return amount clears server confirmation');no($p,fn()=>advance_review($p,$uid,request(identity($changed))),'Stale return confirmation',409);
    $rp['cash_amount']='2000.00';$ret=avsave($p,$uid,'return',$rp,$aid,$changed);$ret=advance_confirm($p,$uid,request(identity($ret)));$returnRequest=avpostrequest($p,$uid,$ret);$rpost=advance_post($p,$uid,$returnRequest);
    $detail=advance_detail($p,$uid,$aid,journal_today());st($detail['status']==='settled'&&$detail['returned']==='2000.00','Unused cash return settles the balance through CRB');
    $snapshot=json_decode($p->query('SELECT review_snapshot FROM cash_advance_operations WHERE journal_id='.$rpost['id'])->fetchColumn(),true);st($snapshot['return_confirmation']['context']['amount']==='2000.00'&&$snapshot['return_confirmation']['confirmed_by']===$uid,'Posted review retains exact confirmed amount and actor');
    $over=avsave($p,$uid,'return',payload([],0,$bank,'1.00'),$aid);$over=avsupport($p,$uid,$over);$over=advance_confirm($p,$uid,request(identity($over)));no($p,fn()=>advance_review($p,$uid,request(identity($over))),'Settled advance refuses further consumption',409);
    // Withholding uses gross evidence and net control reduction.
    $gross=avrelease($p,$uid,(int)$employee['id'],$bank,$ctrl,'4000.00');$gp=payload([line('cost',$training,'4500.00'),line('tax',$tax,'','500.00')]);$gp['line_notes']=['tax'=>'Manual withholding payable; no automated tax calculation'];$gd=avsave($p,$uid,'liquidation',$gp,$gross['advance_id']);$gd=avsupport($p,$uid,$gd,'4500.00');$v=advance_review($p,$uid,request(identity($gd)));st($v['coverage']['debit']['eligible']==='4500.00'&&$v['input']['advance_context']['reduction']==='4000.00','4500 gross less 500 liability requires 4500 proof and reduces advance by 4000');$gpost=advance_post($p,$uid,avpostrequest($p,$uid,$gd));
    $equipment=account_save($p,$uid,'create',['name'=>'Synthetic NGO training equipment','account_type'=>'Asset','account_code'=>'S130','normal_balance'=>'Debit','is_cash_account'=>'0']);$eq=avrelease($p,$uid,(int)$employee2['id'],$bank,$ctrl,'500.00');$ed=avsave($p,$uid,'liquidation',payload([line('cost',$equipment,'500.00')]),$eq['advance_id']);$ed=avsupport($p,$uid,$ed,'500.00');advance_post($p,$uid,avpostrequest($p,$uid,$ed));st(advance_detail($p,$uid,$eq['advance_id'],journal_today())['status']==='settled','Equipment asset liquidation is eligible');
    $date=(new DateTimeImmutable(journal_today()))->modify('-100 days')->format('Y-m-d');$hist=avrelease($p,$uid,(int)$employee['id'],$bank,$ctrl,'100.00',$date,$date);foreach([0,1,30,31,60,61,90,91] as $days){$asof=(new DateTimeImmutable($date))->modify('+'.$days.' days')->format('Y-m-d');$v=advance_detail($p,$uid,$hist['advance_id'],$asof);st($v['overdue_days']===$days,'Historical overdue day boundary '.$days);}
    $newDue=(new DateTimeImmutable(journal_today()))->modify('+10 days')->format('Y-m-d');$v=advance_detail($p,$uid,$hist['advance_id'],journal_today());advance_extend_due($p,$uid,request(['advance_id'=>(string)$hist['advance_id'],'revision'=>(string)$v['revision'],'due_date'=>$newDue,'reason'=>'Synthetic extended field training']));$v=advance_detail($p,$uid,$hist['advance_id'],journal_today());$secondDue=(new DateTimeImmutable($newDue))->modify('+5 days')->format('Y-m-d');advance_extend_due($p,$uid,request(['advance_id'=>(string)$hist['advance_id'],'revision'=>(string)$v['revision'],'due_date'=>$secondDue,'reason'=>'Second same-day extension']));
    st(advance_detail($p,$uid,$hist['advance_id'],journal_today())['due_date']===$secondDue&&advance_detail($p,$uid,$hist['advance_id'],(new DateTimeImmutable(journal_today()))->modify('-1 day')->format('Y-m-d'))['due_date']===$date,'Deadline history applies today and preserves earlier aging');
    $retHist=avsave($p,$uid,'return',payload([],0,$bank,'100.00'),$hist['advance_id']);$retHist=avsupport($p,$uid,$retHist);$retHist=advance_confirm($p,$uid,request(identity($retHist)));advance_post($p,$uid,avpostrequest($p,$uid,$retHist));st(advance_detail($p,$uid,$hist['advance_id'],$date)['outstanding']==='100.00','Currently settled advance remains outstanding at historical date');
    $six=avrelease($p,$uid,(int)$employee['id'],$bank,$ctrl,'6000.00');$four=avrelease($p,$uid,(int)$employee2['id'],$bank,$ctrl,'4000.00');$register=advance_register($p,$uid,['party_id'=>(string)$employee['id']]);$full=array_values(array_filter($register['reconciliation'],fn($r)=>$r['account_id']===$ctrl))[0];st($register['totals']['outstanding']==='6000.00'&&$full['register_balance']==='10000.00'&&$full['ok'],'Filtered employee totals stay separate from full 10000 account reconciliation');
    // Competing full settlements: both review, only one can post.
    $concurrent=avrelease($p,$uid,(int)$employee2['id'],$bank,$ctrl,'120.00');$jobs=[];$workerRequests=[];
    for($i=0;$i<2;$i++){$d=avsave($p,$uid,'liquidation',payload([line('cost',$training,'120.00')]),$concurrent['advance_id']);$d=avsupport($p,$uid,$d,'120.00');$workerRequests[]=avpostrequest($p,$uid,$d);}
    foreach($workerRequests as $i=>$post){$path=$run.'/advance-worker'.$i.'.json';file_put_contents($path,workspace_json(['receipt_root'=>RECEIPT_UPLOAD_DIR,'session'=>$_SESSION,'post'=>$post]));$pipes=[];$proc=proc_open([PHP_BINARY,__FILE__,'--database='.$db,'--worker='.$path],[0=>['pipe','r'],1=>['pipe','w'],2=>['pipe','w']],$pipes);fclose($pipes[0]);$jobs[]=[$proc,$pipes];}
    $out=[];foreach($jobs as [$proc,$pipes]){$data=stream_get_contents($pipes[1]);$err=stream_get_contents($pipes[2]);fclose($pipes[1]);fclose($pipes[2]);cli_require(proc_close($proc)===0,$err);$out[]=json_decode($data,true);}
    st(count(array_filter($out,fn($o)=>$o['ok']))===1&&advance_detail($p,$uid,$concurrent['advance_id'],journal_today())['outstanding']==='0.00','Concurrent settlements consume remaining balance once');
    // Original inactive references stay settleable, unrelated inactive projects do not.
    $inactive=avrelease($p,$uid,(int)$employee2['id'],$bank,$ctrl,'25.00',null,null,(int)$pr['id']);$p->exec('UPDATE parties SET is_active=0 WHERE id='.(int)$employee2['id']);$p->exec('UPDATE projects SET is_active=0 WHERE id='.(int)$pr['id']);
    $idraft=avsave($p,$uid,'liquidation',payload([line('cost',$training,'25.00','',(int)$pr['id'])]),$inactive['advance_id']);$idraft=avsupport($p,$uid,$idraft,'25.00');advance_post($p,$uid,avpostrequest($p,$uid,$idraft));st(advance_detail($p,$uid,$inactive['advance_id'],journal_today())['status']==='settled','Inactive original person and project can be settled using release snapshots');
    $p->exec('UPDATE parties SET is_active=1 WHERE id='.(int)$employee2['id']);$p->exec('UPDATE projects SET is_active=1 WHERE id='.(int)$pr['id']);
    // Existing history privacy and coverage are projected on the server.
    $_SESSION=['UserID'=>(int)$users['management@example.invalid'],'Role'=>'Management'];$muid=(int)$_SESSION['UserID'];$records=accounting_records($p,accounting_records_filters(['from'=>'','to'=>'']));$j=$records['journals'][$gpost['id']];st($j['attachments']===[]&&$j['evidence_coverage']['debit']===['eligible'=>'4500.00','covered'=>'4500.00'],'Management history omits private images while retaining gross coverage');
    st(!isset(advance_detail($p,$muid,$gross['advance_id'],journal_today())['operations'][1]['private_review'])&&receipt_journal_metadata($p,[$gpost['id']])===[],'Management detail and metadata readers omit private review and attachments');
    no($p,fn()=>advance_save($p,$muid,request([])),'Management write',403);$_SESSION=['UserID'=>(int)$users['other@example.invalid'],'Role'=>'Admin'];no($p,fn()=>advance_draft_public($p,(int)$_SESSION['UserID'],(int)$liq['id']),'Advance draft owner isolation',404);
    $_SESSION=['UserID'=>$uid,'Role'=>'Admin'];st(count(receipt_journal_metadata($p,[$gpost['id']])[$gpost['id']])===1,'Admin retains advance evidence access');
    // Link failure occurs after the journal writer: entire transaction must roll back.
    $atomic=avsave($p,$uid,'release',payload([], (int)$employee['id'],$bank,'20.00')+['control_account_id'=>(string)$ctrl,'due_date'=>journal_today()]);$atomicPost=avpostrequest($p,$uid,$atomic);$before=avcount($p);$p->exec("CREATE TRIGGER s2_test_link_failure BEFORE INSERT ON cash_advance_operations FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='fixture link failure'");no($p,fn()=>advance_post($p,$uid,$atomicPost),'Operation-link failure rolls back journal and advance');st(avcount($p)===$before,'No partial journal/advance/evidence state after failed operation link');$p->exec('DROP TRIGGER s2_test_link_failure');
    // Zero-net extra control lines must still fail reconciliation.
    $p->beginTransaction();$j=$six['id'];$s=$p->prepare('INSERT INTO journal_entry_lines(journal_entry_id,account_id,debit_amount,credit_amount) VALUES(?,?,?,?)');$s->execute([$j,$ctrl,'1.00','0.00']);$s->execute([$j,$ctrl,'0.00','1.00']);$state=advance_state($p,journal_today());$r=array_values(array_filter($state['reconciliation'],fn($r)=>$r['account_id']===$ctrl))[0];st($r['difference']==='0.00'&&!$r['ok']&&count($r['errors'])===2,'Bidirectional links detect offsetting unlinked entries with matching net balance');$p->rollBack();
    foreach(['UPDATE cash_advance_operations SET operation_kind=operation_kind','DELETE FROM cash_advance_due_changes','UPDATE cash_advances SET purpose=\'Altered\''] as $sql){try{$p->exec($sql);throw new RuntimeException('Immutable history was accepted');}catch(PDOException $e){st(true,'Immutable advance history rejects '.$sql);}}
    $draftOnly=avsave($p,$uid,'return',payload([],0,$bank,'1.00'),$six['advance_id']);$draftOnly=workspace_attach($p,$uid,request(identity($draftOnly)),stage_image($p,$uid));$removed=workspace_remove_or_discard($p,$uid,request(identity($draftOnly)+['receipt_id'=>$draftOnly['payload']['documents'][0]['receipt_id']]),false);st((int)$removed['payload_version']===3&&$removed['workflow_kind']==='advance_return'&&(int)$removed['advance_id']===$six['advance_id'],'v3 attach/remove preserves workflow and linked advance');$discarded=workspace_remove_or_discard($p,$uid,request(identity($removed)),true);st($discarded['state']==='Discarded'&&(int)$discarded['payload_version']===3,'v3 discard retains context and has no financial effect');
    // Boundary validations keep unsupported / excess work in private drafts.
    $invalid=avsave($p,$uid,'liquidation',payload([line('cost',$training,'6001.00')]),$six['advance_id']);$invalid=avsupport($p,$uid,$invalid,'6001.00');no($p,fn()=>advance_review($p,$uid,request(identity($invalid))),'Supported claim exceeding current advance',409);
    foreach([['cost'=>'100.00','proof'=>'50.00'],['cost'=>'100.00','proof'=>'101.00']] as $case){$d=avsave($p,$uid,'liquidation',payload([line('cost',$training,$case['cost'])]),$six['advance_id']);$d=avsupport($p,$uid,$d,$case['proof']);no($p,fn()=>advance_review($p,$uid,request(identity($d))),'Partial or excessive line evidence '.$case['proof']);}
    $d=avsave($p,$uid,'liquidation',payload([line('cost',$training,'100.00')]),$six['advance_id']);$d=avsupport($p,$uid,$d);no($p,fn()=>advance_review($p,$uid,request(identity($d))),'Informational attachment cannot support expenditure');
    $pbad=payload([line('cost',$training,'100.00'),line('tax',$tax,'','100.00')]);$pbad['line_notes']=['tax'=>'Manual liability'];$d=avsave($p,$uid,'liquidation',$pbad,$six['advance_id']);no($p,fn()=>advance_review($p,$uid,request(identity($d))),'Zero net advance reduction');
    $pbad=payload([line('cost',$training,'100.00'),line('tax',$tax,'','10.00')]);$d=avsave($p,$uid,'liquidation',$pbad,$six['advance_id']);$d=avsupport($p,$uid,$d,'100.00');no($p,fn()=>advance_review($p,$uid,request(identity($d))),'Liability credit without explanation');
    $d=avsave($p,$uid,'liquidation',payload([line('cost',$bank,'10.00')]),$six['advance_id']);no($p,fn()=>advance_review($p,$uid,request(identity($d))),'Liquidation cash-account bypass');
    $bad=payload([], (int)$employee['id'],$bank,'10.00')+['control_account_id'=>(string)$ctrl,'due_date'=>journal_today()];$bad['entry_date']=(new DateTimeImmutable(journal_today()))->modify('+1 day')->format('Y-m-d');$bad['due_date']=$bad['entry_date'];$d=avsave($p,$uid,'release',$bad);no($p,fn()=>advance_review($p,$uid,request(identity($d))),'Future release accounting date',400);
    $bad['entry_date']=journal_today();$bad['due_date']=(new DateTimeImmutable(journal_today()))->modify('-1 day')->format('Y-m-d');$d=avsave($p,$uid,'release',$bad);no($p,fn()=>advance_review($p,$uid,request(identity($d))),'Due date before release');
    $bad['due_date']=journal_today();$bad['approval_name']='Synthetic approver';$d=avsave($p,$uid,'release',$bad);no($p,fn()=>advance_review($p,$uid,request(identity($d))),'Incomplete external approval');
    $bad=payload([],0,$bank,'1.00');$bad['entry_date']=$date;$d=avsave($p,$uid,'return',$bad,$six['advance_id']);$d=avsupport($p,$uid,$d);$d=advance_confirm($p,$uid,request(identity($d)));no($p,fn()=>advance_review($p,$uid,request(identity($d))),'Settlement before release');
    no($p,fn()=>advance_register($p,$uid,['as_of'=>'2026-02-30']),'Invalid historical date',400);no($p,fn()=>advance_register($p,$uid,['party_id'=>['forged']]),'Nonscalar register filter');
    no($p,fn()=>avsave($p,$uid,'return',$d['payload'],$four['advance_id'],$d),'Changing linked advance target',409);
    $bad=$d['payload'];$bad['control_account_id']=(string)$bank;$forged=avsave($p,$uid,'return',$bad,$six['advance_id'],$d);no($p,fn()=>advance_review($p,$uid,request(identity($forged))),'Changing settlement control account',409);
    no($p,fn()=>workspace_attach($p,$uid,request(identity($invalid)),(int)$liq['payload']['documents'][0]['receipt_id']),'Reuse posted liquidation document',409);
    no($p,fn()=>workspace_control($p,$uid,request(['account_id'=>(string)$ctrl,'operation'=>'remove','reason'=>'Test used designation'])),'Removing used control designation');
    // Return before liquidation, then several partial supported settlements.
    $partial=avrelease($p,$uid,(int)$employee['id'],$bank,$ctrl,'100.00');$pd=avsave($p,$uid,'return',payload([],0,$bank,'20.00'),$partial['advance_id']);$pd=avsupport($p,$uid,$pd);$pd=advance_confirm($p,$uid,request(identity($pd)));$confirmed=$pd['payload'];$confirmed['cash_account_id']=(string)$petty;$pd=avsave($p,$uid,'return',$confirmed,$partial['advance_id'],$pd);st($pd['return_confirmation']===null,'Changing return bank clears proof confirmation');$pd=advance_confirm($p,$uid,request(identity($pd)));advance_post($p,$uid,avpostrequest($p,$uid,$pd));
    st(advance_detail($p,$uid,$partial['advance_id'],journal_today())['status']==='partially_settled','Partial cash return before liquidation keeps partial status');
    foreach(['30.00','50.00'] as $amount){$d=avsave($p,$uid,'liquidation',payload([line('cost',$training,$amount)]),$partial['advance_id']);$d=avsupport($p,$uid,$d,$amount);advance_post($p,$uid,avpostrequest($p,$uid,$d));}st(advance_detail($p,$uid,$partial['advance_id'],journal_today())['outstanding']==='0.00','Several partial liquidations settle the remaining advance exactly');
    // Current reconciliation is not derived from historical filters; a read remains one snapshot.
    $pdo2=cli_db($db);$snapDraft=avsave($pdo2,$uid,'release',payload([], (int)$employee['id'],$bank,'1.00')+['control_account_id'=>(string)$ctrl,'due_date'=>journal_today()]);$snapPost=avpostrequest($pdo2,$uid,$snapDraft);$snapResult=null;
    $consistent=accounting_read($p,function()use($p,$pdo2,$uid,$snapPost,&$snapResult){$before=advance_state($p,journal_today());$snapResult=advance_post($pdo2,$uid,$snapPost);$after=advance_state($p,journal_today());return $before===$after;});st($consistent&&isset(advance_state($p,journal_today())['advances'][$snapResult['advance_id']]),'Concurrent posting cannot mix register balances and reconciliation in one read snapshot');
    $d=avsave($p,$uid,'liquidation',payload([line('cost',$training,'1.00')]),$snapResult['advance_id']);$d=avsupport($p,$uid,$d,'1.00');advance_post($p,$uid,avpostrequest($p,$uid,$d));
    $ctrl2=account_save($p,$uid,'create',['name'=>'Synthetic second advance control','account_type'=>'Asset','account_code'=>'S121','normal_balance'=>'Debit','is_cash_account'=>'0']);workspace_control($p,$uid,request(['account_id'=>(string)$ctrl2,'operation'=>'add','reason'=>'Separate synthetic advance arrangement']));
    $p->beginTransaction();$controlLine=(int)$p->query('SELECT control_line_id FROM cash_advance_operations WHERE journal_id='.$six['id'])->fetchColumn();$p->exec('UPDATE journal_entry_lines SET account_id='.$ctrl2.' WHERE id='.$controlLine);$state=advance_state($p,journal_today());st(count(array_filter($state['reconciliation'],fn($r)=>!$r['ok']))===2,'Wrong control account is detected separately on both affected accounts');$p->rollBack();
    st(accounting_integrity($p,journal_today())===[]&&array_reduce(advance_state($p,journal_today())['reconciliation'],fn($ok,$r)=>$ok&&$r['ok'],true),'Final posted journals balance and every control account reconciles');
    file_put_contents($run.'/stage2-fixture.json',workspace_json(['database'=>$db,'receipt_root'=>RECEIPT_UPLOAD_DIR,'employee'=>$employee['id'],'employee2'=>$employee2['id'],'project'=>$pr['id'],'control'=>$ctrl,'bank'=>$bank,'petty'=>$petty,'training'=>$training,'tax'=>$tax,'equipment'=>$equipment,'open_advance'=>$six['advance_id'],'liquidation_journal'=>$gpost['id'],'advance'=>$aid]));
    echo "Stage 2 checks: $checks (plus $stage1Checks Stage 1 checks)\nStage 2 fixture: $run/stage2-fixture.json\n";
}catch(Throwable $e){fwrite(STDERR,$e->getMessage()."\n".$e->getTraceAsString()."\n");exit(1);}
