<?php
/** Synthetic fixtures in a NEW disposable database only; includes Stage 1/2/CP1/CP2 regressions. */
$cp3Options=getopt('',['database:','worker:']);
if(isset($cp3Options['worker'])){
    define('ATIKHA_ISOLATED_TEST',true);
    require_once __DIR__.'/cli_common.php';$workerDb=$cp3Options['database']??'';
    cli_require(is_string($workerDb)&&(bool)preg_match('/\Aatikha_test_stage1_[a-z0-9]+\z/',$workerDb),'Disposable worker required.');
    $path=realpath($cp3Options['worker']);$private=realpath(__DIR__.'/../.migration-private');cli_require($path&&str_starts_with($path,$private.DIRECTORY_SEPARATOR),'Private worker request required.');
    $w=json_decode(file_get_contents($path),true,64,JSON_THROW_ON_ERROR);
    define('STAGE1_WORKSPACE_ENABLED',true);define('STAGE2_ADVANCES_ENABLED',true);define('STAGE3_CORRECTIONS_ENABLED',true);define('OCR_JOURNAL_ENABLED',false);define('RECEIPT_UPLOAD_DIR',$w['receipt_root']);
    require_once __DIR__.'/../includes/correction_posting.php';$_SESSION=$w['session'];$p=cli_db($workerDb);
    try{echo workspace_json(['ok'=>true,'result'=>correction_post($p,$w['uid'],$w['request'])]);}catch(JournalProblem $e){echo workspace_json(['ok'=>false,'status'=>$e->status,'error'=>$e->getMessage()]);}exit;
}
require __DIR__.'/test_stage3_checkpoint2.php';
require_once __DIR__.'/../includes/correction_posting.php';require_once __DIR__.'/../includes/report_snapshots.php';
$regression=$regression+['stage3_checkpoint2'=>$checks];$checks=0;
function cp3request(PDO $p,int $uid,array $d): array {return request(identity($d)+['payload'=>$d['payload'],'review_token'=>correction_review($p,$uid,request(identity($d)))['token']]);}
function cp3payment(PDO $p,int $uid,int $party,int $bank,int $expense,string $amount='1000.00'): array
{
    $d=save($p,$uid,'CDB',payload([line('cp3cost',$expense,$amount)],$party,$bank,$amount));return workspace_post($p,$uid,post_request($p,$uid,$d));
}
function cp3draft(PDO $p,int $uid,int $target,string $amount='900.00',string $mode='reverse_replace'): array
{
    $t=correction_target($p,$target);$d=cdsave($p,$uid,$t,$mode);$v=$d['payload'];$v['reason']='Synthetic correction: payment amount';
    if($v['replacement']){$v['replacement']['cash_amount']=$amount;$v['replacement']['lines'][0]['debit_amount']=$amount;}
    return cdupdate($p,$uid,$d,$v);
}
function cp3manifest(PDO $p): array {return s3manifest($p)+array_combine(['journal_corrections','journal_correction_lines','correction_evidence_reservations','draft_evidence_reservations','accounting_write_state'],array_map(fn($table)=>cp3rows($p,$table),['journal_corrections','journal_correction_lines','correction_evidence_reservations','draft_evidence_reservations','accounting_write_state']));}
function cp3rows(PDO $p,string $table): string {return hash('sha256',workspace_json($p->query('SELECT * FROM '.$table.' ORDER BY 1')->fetchAll()));}
try{
    $_SESSION=['UserID'=>$uid,'Role'=>'Admin'];
    $original=cp3payment($p,$uid,(int)$party['id'],$bank,$training);$t=correction_target($p,$original['id']);$immutable=workspace_json($t['journal']);$originalLines=workspace_json($t['lines']);
    $d=cp3draft($p,$uid,$original['id']);$r=cp3request($p,$uid,$d);
    st(correction_review($p,$uid,request(identity($d)))['posting_available'],'Ordinary review offers posting');
    $broken=$r;$broken['review_token']='0000000000.'.str_repeat('0',64);no($p,fn()=>correction_post($p,$uid,$broken),'Expired review before first post',409);
    $changed=$r;$changed['payload']['reason']='Not saved';no($p,fn()=>correction_post($p,$uid,$changed),'Unsaved submitted content',409);
    $before=accounting_trial_balance($p,journal_today());$out=correction_post($p,$uid,$r);$after=accounting_trial_balance($p,journal_today());
    st(!$out['duplicate']&&$out['replacement_journal_id']!==null,'1000 to 900 posts one complete correction');
    $tAfter=correction_target($p,$original['id']);st(workspace_json($tAfter['journal'])===$immutable&&workspace_json($tAfter['lines'])===$originalLines,'Original header and full lines remain immutable');
    $getNet=fn($tb,$account)=>array_values(array_filter($tb['rows'],fn($v)=>(int)$v['CategoryID']===$account))[0]['net'];
    st(ledger_cents($getNet($after,$bank))-ledger_cents($getNet($before,$bank))===10000&&ledger_cents($getNet($after,$training))-ledger_cents($getNet($before,$training))===-10000,'Corrected ledger effect is 900, not gross CDB 1900');
    $rev=$p->query('SELECT * FROM journal_entries WHERE id='.$out['reversal_journal_id'])->fetch();st($rev['source_book']==='GJ'&&$rev['entry_date']===journal_today(),'Generated reversal goes to GJ on bundle date');
    $count=(int)$p->query('SELECT COUNT(*) FROM journal_entries')->fetchColumn();$_SESSION=['UserID'=>$uid,'Role'=>'Admin'];$r['csrf_token']=csrf_token();$r['review_token']='0000000000.'.str_repeat('0',64);
    $recovered=correction_post($p,$uid,$r);st($recovered['duplicate']&&$recovered['correction_id']===$out['correction_id']&&(int)$p->query('SELECT COUNT(*) FROM journal_entries')->fetchColumn()===$count,'Lost-response retry recovers across new session and expired token');
    $changed['csrf_token']=csrf_token();no($p,fn()=>correction_post($p,$uid,$changed),'Changed-content retry conflicts',409);
    $r['payload']['reason']='changed recovery';no($p,fn()=>correction_post($p,$uid,$r),'Same key with changed content',409);
    $second=cp3draft($p,$uid,$out['replacement_journal_id'],'800.00');$secondOut=correction_post($p,$uid,cp3request($p,$uid,$second));$chain=correction_chain($p,$uid,$secondOut['id']);st(count($chain)===2&&$chain[1]['parent_correction_id']===$out['correction_id'],'Further correction targets replacement and retains root chain');
    no($p,fn()=>correction_review($p,$uid,request(identity($d))),'Corrected target cannot be reviewed again',409);
    no($p,fn()=>cdsave($p,$uid,correction_target($p,$out['reversal_journal_id'])),'Generated reversal cannot be corrected',409);
    $duplicate=cp3payment($p,$uid,(int)$party['id'],$bank,$training);$only=cp3draft($p,$uid,$duplicate['id'],'','reverse_only');$onlyOut=correction_post($p,$uid,cp3request($p,$uid,$only));st($onlyOut['replacement_journal_id']===null&&$onlyOut['id']===$onlyOut['reversal_journal_id'],'Duplicate reverses without a replacement');
    // Real evidence: the original bytes/hash/primary pointer/review remain untouched.
    $image=stage_image($p,$uid);$pd=save($p,$uid,'CDB',payload([line('cp3evidence',$training,'1000.00')],(int)$party['id'],$bank,'1000.00'));$pd=workspace_attach($p,$uid,request(identity($pd)),$image);$pv=$pd['payload'];$pv['documents'][0]=['receipt_id'=>(string)$image,'purpose'=>'amount','support_side'=>'debit','declared_amount'=>'1000.00','accepted_amount'=>'1000.00','exclusion_reason'=>'','reviewed'=>true,'allocations'=>[['client_id'=>'cp3evidence','amount'=>'1000.00']]];$pd=workspace_save($p,$uid,request(identity($pd)+['source_book'=>'CDB','payload'=>$pv]));$ep=workspace_post($p,$uid,post_request($p,$uid,$pd));
    $originalReceipt=workspace_json($p->query('SELECT * FROM Receipts WHERE ReceiptID='.$image)->fetch());$association=$p->query('SELECT * FROM posted_evidence_associations WHERE journal_id='.$ep['id'])->fetch();$ed=cp3draft($p,$uid,$ep['id']);$ed=correction_attach($p,$uid,request(identity($ed)+['receipt_id'=>(string)$image]),true);$pv=$ed['payload'];$pv['replacement']['documents'][0]=['receipt_id'=>(string)$image,'purpose'=>'amount','support_side'=>'debit','declared_amount'=>'1000.00','accepted_amount'=>'900.00','exclusion_reason'=>'Corrected claim','reviewed'=>true,'re_review_reason'=>'Fresh review of corrected amount','allocations'=>[['client_id'=>$pv['replacement']['lines'][0]['client_id'],'amount'=>'900.00']]];$ed=cdupdate($p,$uid,$ed,$pv);
    // Inject each failure after earlier bundle inserts. DDL is only on the disposable DB.
    foreach(['replacement'=>'journal_entries','mapping'=>'journal_correction_lines','allocation'=>'evidence_allocations','audit'=>'audit_logs'] as $label=>$table){
        $condition=$label==='replacement'?"IF NEW.transaction_kind<>'correction_reversal' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Injected replacement failure'; END IF;":"SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Injected $label failure';";
        $p->exec('CREATE TRIGGER cp3_fail BEFORE INSERT ON '.$table.' FOR EACH ROW BEGIN '.$condition.' END');$saved=cp3manifest($p);$request=cp3request($p,$uid,$ed);
        try{correction_post($p,$uid,$request);throw new RuntimeException('Injected failure accepted');}catch(PDOException|RuntimeException $e){if($e->getMessage()==='Injected failure accepted')throw $e;st(cp3manifest($p)===$saved,'Rollback preserves full journal/evidence/draft/reservations at '.$label);}
        $p->exec('DROP TRIGGER cp3_fail');
    }
    $eo=correction_post($p,$uid,cp3request($p,$uid,$ed));$newAssociation=$p->query('SELECT * FROM posted_evidence_associations WHERE journal_id='.$eo['id'])->fetch();st((int)$newAssociation['source_association_id']===(int)$association['id']&&stage3_evidence_association_valid($p,$newAssociation),'Replacement evidence has a validated immediate-target association');
    st(workspace_json($p->query('SELECT * FROM Receipts WHERE ReceiptID='.$image)->fetch())===$originalReceipt&&workspace_json($p->query('SELECT * FROM posted_evidence_associations WHERE id='.$association['id'])->fetch())===workspace_json($association),'Reuse does not rewrite original image or review');
    $again=cp3draft($p,$uid,$eo['id'],'800.00');$again=correction_attach($p,$uid,request(identity($again)+['receipt_id'=>(string)$image]),true);$pv=$again['payload'];$pv['replacement']['documents'][0]=['receipt_id'=>(string)$image,'purpose'=>'amount','support_side'=>'debit','declared_amount'=>'1000.00','accepted_amount'=>'800.00','exclusion_reason'=>'Corrected again','reviewed'=>true,'re_review_reason'=>'Reviewed latest replacement','allocations'=>[['client_id'=>$pv['replacement']['lines'][0]['client_id'],'amount'=>'800.00']]];$again=cdupdate($p,$uid,$again,$pv);$againOut=correction_post($p,$uid,cp3request($p,$uid,$again));st(stage3_evidence_association_valid($p,$p->query('SELECT * FROM posted_evidence_associations WHERE journal_id='.$againOut['id'])->fetch()),'Same bytes can follow a second valid replacement lineage');
    // Stale competitor reservation cleanup, preserving new uploads and unrelated reservations.
    $staleTarget=cp3payment($p,$uid,(int)$party['id'],$bank,$training);$freshImg=stage_image($p,$uid);$sd=save($p,$uid,'CDB',payload([line('stale',$training,'1000.00')],(int)$party['id'],$bank,'1000.00'));$sd=workspace_attach($p,$uid,request(identity($sd)),$freshImg);$pv=$sd['payload'];$pv['documents'][0]['reviewed']=true;$sd=workspace_save($p,$uid,request(identity($sd)+['source_book'=>'CDB','payload'=>$pv]));$sp=workspace_post($p,$uid,post_request($p,$uid,$sd));
    $loser=cp3draft($p,$uid,$sp['id']);$loser=correction_attach($p,$uid,request(identity($loser)+['receipt_id'=>(string)$freshImg]),true);$privateImg=stage_image($p,$uid);$loser=correction_attach($p,$uid,request(identity($loser)+['receipt_id'=>(string)$privateImg]));
    $otherUid=(int)$users['other@example.invalid'];$_SESSION=['UserID'=>$otherUid,'Role'=>'Admin'];$win=cp3draft($p,$otherUid,$sp['id']);$winRequest=cp3request($p,$otherUid,$win);
    $p->exec("CREATE TRIGGER cp3_fail BEFORE INSERT ON audit_logs FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Injected audit failure'");$saved=cp3manifest($p);try{correction_post($p,$otherUid,$winRequest);throw new RuntimeException('Failure accepted');}catch(RuntimeException $e){st(cp3manifest($p)===$saved,'Audit failure rolls back competing reservation cleanup');}$p->exec('DROP TRIGGER cp3_fail');
    $winOut=correction_post($p,$otherUid,$winRequest);st((int)$p->query('SELECT COUNT(*) FROM correction_evidence_reservations WHERE receipt_id='.$freshImg)->fetchColumn()===0,'Successful winner releases exact-target stale reuse reservation');
    st((int)$p->query('SELECT COUNT(*) FROM draft_evidence_reservations WHERE receipt_id='.$privateImg)->fetchColumn()===1&&$p->query('SELECT state FROM journal_drafts WHERE id='.$loser['id'])->fetchColumn()==='Draft','Competing draft and private unposted evidence are preserved');
    $_SESSION=['UserID'=>$uid,'Role'=>'Admin'];no($p,fn()=>correction_review($p,$uid,request(identity($loser))),'Stale competitor review rejected',409);$lr=request(identity($loser)+['payload'=>$loser['payload'],'review_token'=>'0000000000.'.str_repeat('0',64)]);$lr['payload']['replacement']['documents'][0]['reviewed']=true;no($p,fn()=>correction_post($p,$uid,$lr),'Stale competitor post rejected',409);
    // Current references may become inactive: reverse only works; replacement accounts do not.
    $inactive=cp3payment($p,$uid,(int)$party['id'],$bank,$training);$ir=cp3draft($p,$uid,$inactive['id'],'','reverse_only');$p->exec('UPDATE Categories SET Is_Active=0 WHERE CategoryID='.$training);$io=correction_post($p,$uid,cp3request($p,$uid,$ir));st($io['replacement_journal_id']===null,'Exact reversal permits inactive original account');$p->exec('UPDATE Categories SET Is_Active=1 WHERE CategoryID='.$training);
    $active=cp3payment($p,$uid,(int)$party['id'],$bank,$training);$ad=cp3draft($p,$uid,$active['id']);$p->exec('UPDATE Categories SET Is_Active=0 WHERE CategoryID='.$training);no($p,fn()=>correction_review($p,$uid,request(identity($ad))),'Inactive replacement account rejected');$p->exec('UPDATE Categories SET Is_Active=1 WHERE CategoryID='.$training);
    $p->exec('UPDATE parties SET is_active=0 WHERE id='.(int)$party['id']);$allow=correction_post($p,$uid,cp3request($p,$uid,$ad));st($allow['id']>0,'Ordinary replacement may retain original inactive party snapshot');$p->exec('UPDATE parties SET is_active=1 WHERE id='.(int)$party['id']);
    // Changed account/project/party/reference and freshly uploaded proof remain normal validated entries.
    $newExpense=account_save($p,$uid,'create',['name'=>'Synthetic NGO transport correction','account_type'=>'Expense','account_code'=>'CP3510','normal_balance'=>'Debit','is_cash_account'=>'0']);
    $project=workspace_master_save($p,$uid,request(['kind'=>'projects','id'=>'','name'=>'Synthetic NGO training project','code'=>'CP3TRAIN','is_active'=>'1']));
    $changedTarget=cp3payment($p,$uid,(int)$party['id'],$bank,$training);$cd=cp3draft($p,$uid,$changedTarget['id']);$newImage=stage_image($p,$uid);$cd=correction_attach($p,$uid,request(identity($cd)+['receipt_id'=>(string)$newImage]));$pv=$cd['payload'];$pv['replacement']['party_id']=(string)$employee['id'];$pv['replacement']['reference']='Corrected supplier / project';$pv['replacement']['lines'][0]['account_id']=(string)$newExpense;$pv['replacement']['lines'][0]['fund_project_id']=(string)$project['id'];$pv['replacement']['documents'][0]['reviewed']=true;$cd=cdupdate($p,$uid,$cd,$pv);$co=correction_post($p,$uid,cp3request($p,$uid,$cd));
    $header=$p->query('SELECT * FROM journal_entries WHERE id='.$co['id'])->fetch();$line=$p->query('SELECT * FROM journal_entry_lines WHERE journal_entry_id='.$co['id'].' AND account_id='.$newExpense)->fetch();st((int)$header['party_id']===(int)$employee['id']&&$header['reference']==='Corrected supplier / project'&&(int)$line['fund_project_id']===(int)$project['id'],'Replacement validates and records changed account/project/party/reference');st((int)$p->query('SELECT JournalEntryID FROM Receipts WHERE ReceiptID='.$newImage)->fetchColumn()===$co['id'],'New evidence gets replacement primary pointer');
    $retained=cp3draft($p,$uid,$co['id']);$p->exec('UPDATE projects SET is_active=0 WHERE id='.(int)$project['id']);$retainOut=correction_post($p,$uid,cp3request($p,$uid,$retained));st($retainOut['id']>0,'Ordinary replacement may retain original inactive project snapshot');$p->exec('UPDATE projects SET is_active=1 WHERE id='.(int)$project['id']);
    $transfer=save($p,$uid,'GJ',payload([line('cp3in',$petty,'50.00'),line('cp3out',$bank,'','50.00')]));$pv=$transfer['payload'];$pv['transaction_kind']='transfer';$transfer=workspace_save($p,$uid,request(identity($transfer)+['source_book'=>'GJ','payload'=>$pv]));$transferOut=workspace_post($p,$uid,post_request($p,$uid,$transfer));$td=cdsave($p,$uid,correction_target($p,$transferOut['id']));$pv=$td['payload'];$pv['reason']='Correct transfer reference';$pv['replacement']['reference']='TRANSFER-FIX';$td=cdupdate($p,$uid,$td,$pv);$to=correction_post($p,$uid,cp3request($p,$uid,$td));st($p->query('SELECT transaction_kind FROM journal_entries WHERE id='.$to['id'])->fetchColumn()==='transfer','Cash transfer replacement remains validated GJ transfer');
    $legacyId=(int)$p->query("SELECT id FROM journal_entries WHERE source_book IS NULL AND NOT EXISTS(SELECT 1 FROM journal_corrections c WHERE c.target_journal_id=journal_entries.id) LIMIT 1")->fetchColumn();$ld=cdsave($p,$uid,correction_target($p,$legacyId));$pv=$ld['payload'];$pv['reason']='Correct legacy reference';$ld=cdupdate($p,$uid,$ld,$pv);$lo=correction_post($p,$uid,cp3request($p,$uid,$ld));st($p->query('SELECT source_book FROM journal_entries WHERE id='.$legacyId)->fetchColumn()===null&&$p->query('SELECT source_book FROM journal_entries WHERE id='.$lo['id'])->fetchColumn()==='GJ','Legacy original stays unclassified; replacement defaults to GJ');
    // Snapshot figures and review state stay frozen, including net-zero metadata corrections.
    $meta=cp3payment($p,$uid,(int)$party['id'],$bank,$training);$md=cp3draft($p,$uid,$meta['id'],'1000.00');$pv=$md['payload'];$pv['replacement']['reference']='Corrected reference';$md=cdupdate($p,$uid,$md,$pv);$asOf=journal_today();$year=(int)substr($asOf,0,4);$month=(int)substr($asOf,5,2);$end=accounting_month_end($year,$month);$source=accounting_trial_balance($p,$end);$snapshot=report_snapshot_submit($p,$uid,request(['report_year'=>(string)$year,'report_month'=>(string)$month,'source_fingerprint'=>$source['fingerprint'],'submission_key'=>report_submission_token($year,$month,$source['fingerprint'])]));$_SESSION=['UserID'=>(int)$users['management@example.invalid'],'Role'=>'Management'];report_snapshot_review($p,(int)$_SESSION['UserID'],request(['entity_id'=>(string)$snapshot['id'],'review_notes'=>'Synthetic reviewed baseline']));$_SESSION=['UserID'=>$uid,'Role'=>'Admin'];$tb=accounting_trial_balance($p,$asOf);$oldTb=accounting_trial_balance($p,'2020-01-01');$frozen=cp3rows($p,'trial_balance_snapshots');$frozenLines=cp3rows($p,'trial_balance_snapshot_lines');$mo=correction_post($p,$uid,cp3request($p,$uid,$md));$tbAfter=accounting_trial_balance($p,$asOf);
    st($tb['rows']===$tbAfter['rows']&&$tb['fingerprint']!==$tbAfter['fingerprint'],'Net-zero metadata correction changes live fingerprint without changing balances');st(cp3rows($p,'trial_balance_snapshots')===$frozen&&cp3rows($p,'trial_balance_snapshot_lines')===$frozenLines,'Existing frozen revisions and review states are unchanged');st(accounting_trial_balance($p,'2020-01-01')===$oldTb,'Out-of-range correction leaves prior report unchanged');
    // Two separately reviewed Admin requests race on the same target under the shared barrier.
    $race=cp3payment($p,$uid,(int)$party['id'],$bank,$training);$ra=cp3draft($p,$uid,$race['id']);$qa=cp3request($p,$uid,$ra);$sa=$_SESSION;$_SESSION=['UserID'=>$otherUid,'Role'=>'Admin'];$rb=cp3draft($p,$otherUid,$race['id'],'950.00');$qb=cp3request($p,$otherUid,$rb);$sb=$_SESSION;$workers=[];
    foreach([[$uid,$qa,$sa],[$otherUid,$qb,$sb]] as $i=>[$actor,$q,$session]){$file=$run.'/cp3-worker-'.$i.'.json';file_put_contents($file,workspace_json(['uid'=>$actor,'request'=>$q,'session'=>$session,'receipt_root'=>RECEIPT_UPLOAD_DIR]));$pipes=[];$proc=proc_open([PHP_BINARY,__FILE__,'--database='.$db,'--worker='.$file],[0=>['pipe','r'],1=>['pipe','w'],2=>['pipe','w']],$pipes);fclose($pipes[0]);$workers[]=[$proc,$pipes];}
    $results=[];foreach($workers as [$proc,$pipes]){$json=stream_get_contents($pipes[1]);$err=stream_get_contents($pipes[2]);fclose($pipes[1]);fclose($pipes[2]);cli_require(proc_close($proc)===0&&$err==='','Race worker failed: '.$err);$results[]=json_decode($json,true,64,JSON_THROW_ON_ERROR);}
    st(count(array_filter($results,fn($v)=>$v['ok']))===1&&(int)$p->query('SELECT COUNT(*) FROM journal_corrections WHERE target_journal_id='.$race['id'])->fetchColumn()===1,'Concurrent Admin corrections commit exactly one bundle');
    $_SESSION=['UserID'=>$uid,'Role'=>'Admin'];$advanced=correction_draft($p,$uid,(int)$liqDraft['id']);no($p,fn()=>correction_post($p,$uid,request(identity($advanced)+['payload'=>$advanced['payload'],'review_token'=>''])),'Advance first posting still requires a valid review token',409);
    $bookRecords=accounting_records($p,accounting_records_filters(['view'=>'cdb','from'=>'','to'=>'']));st(isset($bookRecords['journals'][$out['target_journal_id']],$bookRecords['journals'][$out['replacement_journal_id']])&&!isset($bookRecords['journals'][$out['reversal_journal_id']]),'CDB retains gross original/replacement activity and GJ holds offset');$records=accounting_records($p,accounting_records_filters(['from'=>'','to'=>'']));st($records['journals'][$out['reversal_journal_id']]['corrections'][0]['role']==='Generated GJ reversal'&&str_contains(workspace_json($records['rows']),'Synthetic correction: payment amount'),'History metadata/search exposes financial correction context');$_SESSION=['UserID'=>(int)$users['management@example.invalid'],'Role'=>'Management'];$permitted=correction_posted_detail($p,(int)$_SESSION['UserID'],$last['replacement']);st(!str_contains(workspace_json($permitted),'secret-review')&&$permitted['journals'][$last['replacement']]['attachments']===[]&&$permitted['journals'][$last['replacement']]['evidence_coverage']['status']==='Fully covered','Management posted comparison preserves coverage and redacts private advance evidence');$_SESSION=['UserID'=>$uid,'Role'=>'Admin'];
    st(correction_integrity($p)===[],'Final full-chain, evidence, reservation and control integrity passes');
    $browserTarget=cp3payment($p,$uid,(int)$party['id'],$bank,$training);
    file_put_contents($run.'/stage3-checkpoint3-fixture.json',workspace_json(['database'=>$db,'receipt_root'=>RECEIPT_UPLOAD_DIR,'payment_target'=>$browserTarget['id'],'posted_draft'=>$md['id'],'stale_draft'=>$loser['id'],'bank'=>$bank,'training'=>$training,'party'=>$party['id'],'private_advance_journal'=>$last['replacement']]));
    echo 'Stage 3 checkpoint 3 checks: '.$checks."\nRegression checks: ".workspace_json($regression)."\nFixture: $run/stage3-checkpoint3-fixture.json\n";
}catch(Throwable $e){if($p->inTransaction())$p->rollBack();fwrite(STDERR,$e->getMessage()."\n".$e->getTraceAsString()."\n");exit(1);}
