<?php
/** New disposable database only. Never reads working config or uses working receipts. */
$cp4Options=getopt('',['database:','cp4-worker:']);
if(isset($cp4Options['cp4-worker'])){
    define('ATIKHA_ISOLATED_TEST',true);require_once __DIR__.'/cli_common.php';$workerDb=$cp4Options['database']??'';
    cli_require(is_string($workerDb)&&(bool)preg_match('/\Aatikha_test_stage1_[a-z0-9]+\z/',$workerDb),'Disposable worker required.');
    $path=realpath($cp4Options['cp4-worker']);$base=realpath(__DIR__.'/../.migration-private');cli_require($path&&str_starts_with($path,$base.DIRECTORY_SEPARATOR),'Private worker required.');$w=json_decode(file_get_contents($path),true,64,JSON_THROW_ON_ERROR);
    $evidence=realpath($w['receipt_root']);cli_require($evidence&&str_starts_with($evidence,$base.DIRECTORY_SEPARATOR),'Private evidence required.');
    define('STAGE1_WORKSPACE_ENABLED',true);define('STAGE2_ADVANCES_ENABLED',true);define('STAGE3_CORRECTIONS_ENABLED',true);define('OCR_JOURNAL_ENABLED',false);define('RECEIPT_UPLOAD_DIR',$evidence);
    require_once __DIR__.'/../includes/correction_posting.php';$_SESSION=$w['session'];$p=cli_db($workerDb);
    try{$fn=$w['kind']==='advance'?'advance_post':'correction_post';echo workspace_json(['ok'=>true,'result'=>$fn($p,$w['uid'],$w['request'])]);}catch(JournalProblem $e){echo workspace_json(['ok'=>false,'status'=>$e->status,'error'=>$e->getMessage()]);}exit;
}
require __DIR__.'/test_stage3_checkpoint3.php';
$regression+=['stage3_checkpoint3'=>$checks];$checks=0;
function cp4date(int $offset): string {return (new DateTimeImmutable(journal_today(),new DateTimeZone('Asia/Manila')))->modify(($offset>=0?'+':'').$offset.' days')->format('Y-m-d');}
function cp4liq(PDO $p,int $uid,int $advance,int $cost,string $amount,string $date,?int $tax=null,string $liability=''): array
{
    $lines=[line('cost',$cost,$amount)];if($tax!==null)$lines[]=line('tax',$tax,'',$liability);$pv=payload($lines);$pv['entry_date']=$date;$pv['line_notes']=$tax===null?[]:['tax'=>'Synthetic manually reviewed withholding'];$d=avsave($p,$uid,'liquidation',$pv,$advance);$d=avsupport($p,$uid,$d,$amount);$request=avpostrequest($p,$uid,$d);return advance_post($p,$uid,$request)+['draft'=>$d,'post'=>$request];
}
function cp4return(PDO $p,int $uid,int $advance,int $cash,string $amount,string $date): array
{
    $pv=payload([],0,$cash,$amount);$pv['entry_date']=$date;$d=avsave($p,$uid,'return',$pv,$advance);$d=avsupport($p,$uid,$d);$d=advance_confirm($p,$uid,request(identity($d)));$r=avpostrequest($p,$uid,$d);return advance_post($p,$uid,$r)+['draft'=>$d,'post'=>$r];
}
function cp4draft(PDO $p,int $uid,int $journal,string $date,?string $amount=null,bool $only=false): array
{
    $t=correction_target($p,$journal);$d=cdsave($p,$uid,$t,$only?'reverse_only':'reverse_replace');$pv=$d['payload'];$pv['entry_date']=$date;$pv['reason']='Synthetic NGO correction';$pv['backdate_reason']='Verified synthetic historical date';
    if($pv['replacement']){if($t['operation']['operation_kind']==='liquidation'){$pv['replacement']['lines'][0]['debit_amount']=$amount??$pv['replacement']['lines'][0]['debit_amount'];foreach($pv['replacement']['lines'] as $l)if(journal_amount($l['credit_amount'])>0)$pv['replacement']['line_notes'][$l['client_id']]='Reviewed synthetic liability';}else $pv['replacement']['cash_amount']=$amount??$pv['replacement']['cash_amount'];if($t['operation']['operation_kind']==='release')$pv['replacement']['due_date']=cp4date(2);}
    return cdupdate($p,$uid,$d,$pv);
}
function cp4support(PDO $p,int $uid,array $d,bool $reuse=true): array
{
    if($reuse){$s=$p->prepare('SELECT receipt_id FROM posted_evidence_associations WHERE journal_id=? LIMIT 1');$s->execute([$d['correction_target_journal_id']]);$image=(int)$s->fetchColumn();$d=correction_attach($p,$uid,request(identity($d)+['receipt_id'=>(string)$image]),true);}
    else{$image=stage_image($p,$uid);$d=correction_attach($p,$uid,request(identity($d)+['receipt_id'=>(string)$image]));}
    $pv=$d['payload'];$kind=correction_target($p,(int)$d['correction_target_journal_id'])['operation']['operation_kind'];$doc=&$pv['replacement']['documents'][count($pv['replacement']['documents'])-1];$doc['reviewed']=true;$doc['re_review_reason']='Fresh review for corrected claim';
    if($kind==='liquidation'){$gross=0;$alloc=[];foreach($pv['replacement']['lines'] as $l)if(journal_amount($l['debit_amount'])>0){$gross=accounting_add($gross,journal_amount($l['debit_amount']));$alloc[]=['client_id'=>$l['client_id'],'amount'=>$l['debit_amount']];}$doc['purpose']='amount';$doc['support_side']='debit';$doc['declared_amount']=$doc['accepted_amount']=ledger_decimal($gross);$doc['allocations']=$alloc;}
    unset($doc);return cdupdate($p,$uid,$d,$pv);
}
function cp4manifest(PDO $p): array {return cp3manifest($p)+['cash_advance_operation_reversals'=>cp3rows($p,'cash_advance_operation_reversals')];}
function cp4race(PDO $p,string $db,string $run,array $jobs): array
{
    $workers=[];foreach($jobs as $i=>$job){$path=$run.'/cp4-worker-'.bin2hex(random_bytes(4)).'.json';file_put_contents($path,workspace_json($job+['receipt_root'=>RECEIPT_UPLOAD_DIR]));$pipes=[];$proc=proc_open([PHP_BINARY,__FILE__,'--database='.$db,'--cp4-worker='.$path],[0=>['pipe','r'],1=>['pipe','w'],2=>['pipe','w']],$pipes);fclose($pipes[0]);$workers[]=[$proc,$pipes];}
    $results=[];foreach($workers as [$proc,$pipes]){$json=stream_get_contents($pipes[1]);$err=stream_get_contents($pipes[2]);fclose($pipes[1]);fclose($pipes[2]);cli_require(proc_close($proc)===0&&$err==='','Worker error: '.$err);$results[]=json_decode($json,true,64,JSON_THROW_ON_ERROR);}return $results;
}
try{
    $_SESSION=['UserID'=>$uid,'Role'=>'Admin'];$employeeId=(int)$employee['id'];
    $release=avrelease($p,$uid,$employeeId,$bank,$ctrl,'10000.00',cp4date(-5),cp4date(-4));$a=$release['advance_id'];$liq=cp4liq($p,$uid,$a,$training,'8000.00',cp4date(-4));$d=cp4draft($p,$uid,$liq['id'],cp4date(-2),'7000.00');$d=cp4support($p,$uid,$d);$review=correction_review($p,$uid,request(identity($d)));
    st($review['posting_available']&&$review['advance_effect']['before']===200000&&$review['advance_effect']['after']===300000,'Liquidation review predicts exact before/after and enables posting');
    $request=cp3request($p,$uid,$d);$out=correction_post($p,$uid,$request);st($out['original_advance_id']===$a&&$out['replacement_advance_id']===null&&$out['advance_id']===$a,'Liquidation replacement retains original advance');
    st(advance_detail($p,$uid,$a,cp4date(-3))['outstanding']==='2000.00'&&advance_detail($p,$uid,$a,cp4date(-2))['outstanding']==='3000.00','Liquidation original 8000 and replacement 7000 project correctly before/after correction');
    st(advance_detail($p,$uid,$a,cp4date(-3))['overdue_days']===1&&advance_detail($p,$uid,$a,journal_today())['overdue_days']===4,'Correction-aware historical aging uses dated deadlines');
    $snapshot=json_decode($p->query('SELECT review_snapshot FROM journal_corrections WHERE id='.$out['correction_id'])->fetchColumn(),true);st($snapshot['advance_effect']['after']===300000&&$snapshot['original_advance_id']===$a,'Immutable correction snapshot records advance effects and identity');
    $manifest=cp4manifest($p);$_SESSION=['UserID'=>$uid,'Role'=>'Admin'];$request['csrf_token']=csrf_token();$request['review_token']='0000000000.'.str_repeat('0',64);$recover=correction_post($p,$uid,$request);st($recover['duplicate']&&$recover['correction_id']===$out['correction_id']&&cp4manifest($p)===$manifest,'Liquidation retry after login/expiry returns same result with no write');
    $originalRetry=$liq['post'];$originalRetry['csrf_token']=csrf_token();$originalRetry['review_token']='';st(advance_post($p,$uid,$originalRetry)['id']===$liq['id']&&cp4manifest($p)===$manifest,'Original liquidation request replay after correction returns original journal');
    st(!correction_target($p,$release['id'])['eligible'],'Replacement liquidation still blocks release correction');
    $bad=$request;$bad['payload']['replacement']['line_notes'][$bad['payload']['replacement']['lines'][0]['client_id']]='Changed durable field';no($p,fn()=>correction_post($p,$uid,$bad),'Changed advance-specific retry content',409);
    $ret=cp4return($p,$uid,$a,$bank,'3000.00',cp4date(-1));$rd=cp4draft($p,$uid,$ret['id'],journal_today(),'2500.00');$rd=cp4support($p,$uid,$rd);no($p,fn()=>correction_review($p,$uid,request(identity($rd))),'Return correction lacks fresh confirmation',409);$rd=correction_confirm($p,$uid,request(identity($rd)));$rq=cp3request($p,$uid,$rd);$ro=correction_post($p,$uid,$rq);st(advance_detail($p,$uid,$a,journal_today())['outstanding']==='500.00'&&advance_detail($p,$uid,$a,cp4date(-1))['outstanding']==='0.00','Return replacement restores 500 today while prior day stays settled');
    $manifest=cp4manifest($p);$rr=$ret['post'];$rr['review_token']='';st(advance_post($p,$uid,$rr)['id']===$ret['id']&&cp4manifest($p)===$manifest,'Original return replay recovers original after correction');$rq['review_token']='';st(correction_post($p,$uid,$rq)['duplicate']&&cp4manifest($p)===$manifest,'Return correction expired retry recovers same operation');
    $saved=json_decode($p->query('SELECT review_snapshot FROM cash_advance_operations WHERE journal_id='.$ro['id'])->fetchColumn(),true);st($saved['return_confirmation']['context']['amount']==='2500.00'&&$saved['return_confirmation']['context']['advance_id']===$a,'Return replacement operation preserves amount-bound proof context');
    $grossRelease=avrelease($p,$uid,$employeeId,$bank,$ctrl,'10000.00',cp4date(-5),cp4date(2));$grossLiq=cp4liq($p,$uid,$grossRelease['advance_id'],$training,'4500.00',cp4date(-4),$tax,'500.00');$gd=cp4draft($p,$uid,$grossLiq['id'],cp4date(-2),'4500.00');$gd=cp4support($p,$uid,$gd);$gr=correction_review($p,$uid,request(identity($gd)));$go=correction_post($p,$uid,cp3request($p,$uid,$gd));st($gr['coverage']['debit']['eligible']==='4500.00'&&$gr['input']['advance_context']['reduction']==='4000.00'&&advance_detail($p,$uid,$grossRelease['advance_id'],journal_today())['outstanding']==='6000.00','Withholding correction supports gross 4500, credits liability 500 and reduces advance 4000');
    $assetDraft=cp4draft($p,$uid,$go['id'],journal_today(),'4500.00');$pv=$assetDraft['payload'];$pv['replacement']['lines'][0]['account_id']=(string)$equipment;$assetDraft=cdupdate($p,$uid,$assetDraft,$pv);$assetDraft=cp4support($p,$uid,$assetDraft);$assetOut=correction_post($p,$uid,cp3request($p,$uid,$assetDraft));st(advance_detail($p,$uid,$grossRelease['advance_id'],journal_today())['outstanding']==='6000.00','Eligible equipment replacement uses same gross coverage and net reduction');
    $ctrl2=account_save($p,$uid,'create',['name'=>'Synthetic second employee advance control','account_code'=>'CP4131','account_type'=>'Asset','normal_balance'=>'Debit','is_cash_account'=>'0']);workspace_control($p,$uid,request(['account_id'=>(string)$ctrl2,'operation'=>'add','reason'=>'Synthetic second control']));
    $newRelease=avrelease($p,$uid,$employeeId,$bank,$ctrl,'10000.00',cp4date(-5),cp4date(-4));$old=$newRelease['advance_id'];$oldRow=workspace_json(advance_load($p,$old));$nd=cp4draft($p,$uid,$newRelease['id'],cp4date(-2),'9000.00');$pv=$nd['payload'];$pv['replacement']['control_account_id']=(string)$ctrl2;$pv['replacement']['party_id']=(string)$employee2['id'];$pv['replacement']['approval_name']='Synthetic authorized manager';$pv['replacement']['approval_date']=cp4date(-2);$pv['replacement']['approval_reference']='DEMO';$nd=cdupdate($p,$uid,$nd,$pv);
    foreach(['operation_reversal'=>'cash_advance_operation_reversals','new_identity'=>'cash_advances','new_operation'=>'cash_advance_operations','final_audit'=>'audit_logs'] as $label=>$table){$p->exec("CREATE TRIGGER cp4_fail BEFORE INSERT ON $table FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Injected $label failure'");$baseline=cp4manifest($p);try{correction_post($p,$uid,cp3request($p,$uid,$nd));throw new RuntimeException('Injected failure accepted');}catch(PDOException|RuntimeException $e){if($e->getMessage()==='Injected failure accepted')throw $e;st(cp4manifest($p)===$baseline,'Complete rollback at '.$label);}finally{$p->exec('DROP TRIGGER cp4_fail');}}
    $nq=cp3request($p,$uid,$nd);$no=correction_post($p,$uid,$nq);$new=$no['replacement_advance_id'];$oldDetail=advance_detail($p,$uid,$old,journal_today());$newDetail=advance_detail($p,$uid,$new,journal_today());
    st($new!==$old&&$no['advance_id']===$new&&$oldDetail['status']==='replaced'&&$newDetail['outstanding']==='9000.00','Release replacement creates new number and retires old advance');st($oldDetail['original_released']==='10000.00'&&$oldDetail['released']==='0.00'&&!$oldDetail['can_settle']&&!$oldDetail['overdue'],'Retired release preserves original gross and zero effective/overdue balance');st(advance_detail($p,$uid,$old,cp4date(-3))['status']==='outstanding'&&$newDetail['original_advance_id']===$old,'Historical old lifecycle and new original link are correct');
    st((int)correction_draft($p,$uid,(int)$nd['id'])['advance_id']===$old&&correction_public($p,$uid,correction_draft($p,$uid,(int)$nd['id']))['posted_result']['replacement_advance_id']===$new,'v4 draft retains old ID while reopening navigates new ID');
    $state=advance_state($p,journal_today());st(count(array_filter($state['reconciliation'],fn($r)=>in_array($r['account_id'],[$ctrl,$ctrl2],true)&&$r['ok']))===2,'Old and new control accounts independently reconcile');
    $nq['review_token']='';$baseline=cp4manifest($p);st(correction_post($p,$uid,$nq)['replacement_advance_id']===$new&&cp4manifest($p)===$baseline,'Release correction retry never creates another advance');$or=$newRelease['post'];$or['review_token']='';st(advance_post($p,$uid,$or)['advance_id']===$old&&cp4manifest($p)===$baseline,'Original release replay returns old identity after replacement');
    foreach(['due_date'=>cp4date(3),'control_account_id'=>(string)$ctrl,'approval_reference'=>'changed'] as $key=>$value){$bad=$nq;$bad['payload']['replacement'][$key]=$value;no($p,fn()=>correction_post($p,$uid,$bad),'Durable release field conflict '.$key,409);}
    no($p,fn()=>advance_extend_due($p,$uid,request(['advance_id'=>(string)$old,'revision'=>(string)$oldDetail['revision'],'due_date'=>cp4date(5),'reason'=>'Invalid extension'])),'Retired advance deadline cannot extend');
    $invalid=avsave($p,$uid,'liquidation',payload([line('cost',$training,'1.00')]),$old);$invalid=avsupport($p,$uid,$invalid,'1.00');no($p,fn()=>advance_review($p,$uid,request(identity($invalid))),'Retired advance cannot receive new settlement',409);
    // Successive new release identities and recovery of a previously corrected replacement.
    $nn=cp4draft($p,$uid,$no['id'],journal_today(),'8500.00');$nno=correction_post($p,$uid,cp3request($p,$uid,$nn));st($nno['original_advance_id']===$new&&$nno['replacement_advance_id']!==$new&&advance_detail($p,$uid,$new,journal_today())['status']==='replaced','Further release correction creates another identity without rewriting old links');st(correction_post($p,$uid,$nq)['replacement_advance_id']===$new,'Earlier successful retry preserves its own replacement after later correction');
    // Historical release dependencies and normal backdated settlement protection.
    $history=avrelease($p,$uid,$employeeId,$bank,$ctrl,'10000.00',cp4date(-5),cp4date(2));$hl=cp4liq($p,$uid,$history['advance_id'],$training,'8000.00',cp4date(-4));$hd=cp4draft($p,$uid,$hl['id'],journal_today(),null,true);correction_post($p,$uid,cp3request($p,$uid,$hd));$early=cp4draft($p,$uid,$history['id'],cp4date(-1),null,true);no($p,fn()=>correction_review($p,$uid,request(identity($early))),'Release reversal cannot predate settlement reversal',409);
    $bp=payload([line('cost',$training,'8000.00')]);$bp['entry_date']=cp4date(-3);$bd=avsave($p,$uid,'liquidation',$bp,$history['advance_id']);$bd=avsupport($p,$uid,$bd,'8000.00');no($p,fn()=>advance_review($p,$uid,request(identity($bd))),'Normal settlement cannot consume future-restored balance',409);$bp=$bd['payload'];$bp['entry_date']=journal_today();$bd=avsave($p,$uid,'liquidation',$bp,$history['advance_id'],$bd);$bo=advance_post($p,$uid,avpostrequest($p,$uid,$bd));st(advance_detail($p,$uid,$history['advance_id'],journal_today())['outstanding']==='2000.00','Same-day restored balance can fund a valid normal settlement');
    $hb=cp4draft($p,$uid,$bo['id'],journal_today(),null,true);correction_post($p,$uid,cp3request($p,$uid,$hb));$cancel=cp4draft($p,$uid,$history['id'],journal_today(),null,true);$cancelOut=correction_post($p,$uid,cp3request($p,$uid,$cancel));st(advance_detail($p,$uid,$history['advance_id'],journal_today())['status']==='cancelled','Release reversal-only cancels after all effective dependencies clear');
    // Fresh release replacement references must remain active at posting.
    $active=avrelease($p,$uid,$employeeId,$bank,$ctrl,'100.00',cp4date(-3),cp4date(2),(int)$pr['id']);$ad=cp4draft($p,$uid,$active['id'],journal_today(),'90.00');$aq=cp3request($p,$uid,$ad);$p->exec('UPDATE parties SET is_active=0 WHERE id='.$employeeId);no($p,fn()=>correction_post($p,$uid,$aq),'Release employee deactivated after review');$p->exec('UPDATE parties SET is_active=1 WHERE id='.$employeeId);$p->exec('UPDATE projects SET is_active=0 WHERE id='.(int)$pr['id']);no($p,fn()=>correction_review($p,$uid,request(identity($ad))),'Release inactive project rejected');$p->exec('UPDATE projects SET is_active=1 WHERE id='.(int)$pr['id']);
    $sett=cp4liq($p,$uid,$active['advance_id'],$training,'50.00',journal_today());$sd=cp4draft($p,$uid,$sett['id'],journal_today(),'40.00');$sd=cp4support($p,$uid,$sd);$p->exec('UPDATE parties SET is_active=0 WHERE id='.$employeeId);$p->exec('UPDATE projects SET is_active=0 WHERE id='.(int)$pr['id']);$so=correction_post($p,$uid,cp3request($p,$uid,$sd));st(advance_detail($p,$uid,$active['advance_id'],journal_today())['outstanding']==='60.00','Linked settlement replacement retains narrow inactive original context');$p->exec('UPDATE parties SET is_active=1 WHERE id='.$employeeId);$p->exec('UPDATE projects SET is_active=1 WHERE id='.(int)$pr['id']);
    // Offset corruption, partial schema and legitimate v4 context checks are read-only in transactions.
    $p->beginTransaction();$p->prepare("INSERT INTO journal_entry_lines(journal_entry_id,account_id,debit_amount,credit_amount) VALUES(?,?,1,0),(?,?,0,1)")->execute([$newRelease['id'],$ctrl,$newRelease['id'],$ctrl]);st(correction_control_integrity($p)!==[],'Offsetting unlinked controls cannot hide behind matching net balance');$p->rollBack();
    $p->beginTransaction();$p->exec('UPDATE journal_drafts SET advance_id='.$old.' WHERE id='.(int)$nn['id']);st(correction_control_integrity($p)!==[],'Forged v4 original/new identity fails reconciliation');$p->rollBack();
    $filtered=advance_register($p,$uid,['status'=>'replaced']);st(count($filtered['rows'])>=2&&$filtered['totals']['outstanding']==='0.00'&&!array_filter($filtered['reconciliation'],fn($r)=>!$r['ok']),'Replaced filter totals are separate from full-account reconciliation');
    $_SESSION=['UserID'=>(int)$users['management@example.invalid'],'Role'=>'Management'];$mdetail=advance_detail($p,(int)$_SESSION['UserID'],$a,journal_today());$comparison=correction_posted_detail($p,(int)$_SESSION['UserID'],$out['id']);st(!str_contains(workspace_json($mdetail),'receipt_attachment.php')&&!str_contains(workspace_json($mdetail),'return_confirmation')&&!str_contains(workspace_json($comparison),'receipt_attachment.php')&&$comparison['journals'][$out['id']]['evidence_coverage']['status']==='Fully covered','Management receives financial correction timeline and truthful coverage without private proof');$_SESSION=['UserID'=>$uid,'Role'=>'Admin'];
    // Two connections: settlement corrections, release corrections, correction versus normal settlement.
    foreach(['liquidation','release','mixed'] as $kind){$race=avrelease($p,$uid,$employeeId,$bank,$ctrl,'100.00');$target=$kind==='release'?$race:cp4liq($p,$uid,$race['advance_id'],$training,'80.00',journal_today());$jobs=[];
        $da=cp4draft($p,$uid,$target['id'],journal_today(),$kind==='release'?'90.00':'70.00');if($kind!=='release')$da=cp4support($p,$uid,$da,false);$qa=cp3request($p,$uid,$da);$jobs[]=['kind'=>'correction','uid'=>$uid,'session'=>$_SESSION,'request'=>$qa];
        if($kind==='mixed'){$vb=avsave($p,$uid,'liquidation',payload([line('cost',$training,'20.00')]),$race['advance_id']);$vb=avsupport($p,$uid,$vb,'20.00');$qb=avpostrequest($p,$uid,$vb);$jobs[]=['kind'=>'advance','uid'=>$uid,'session'=>$_SESSION,'request'=>$qb];}
        else{$_SESSION=['UserID'=>$otherUid,'Role'=>'Admin'];$dbb=cp4draft($p,$otherUid,$target['id'],journal_today(),$kind==='release'?'95.00':'75.00');if($kind!=='release')$dbb=cp4support($p,$otherUid,$dbb,false);$qb=cp3request($p,$otherUid,$dbb);$jobs[]=['kind'=>'correction','uid'=>$otherUid,'session'=>$_SESSION,'request'=>$qb];}
        $results=cp4race($p,$db,$run,$jobs);st(count(array_filter($results,fn($r)=>$r['ok']))===1,'Concurrent '.$kind.' requests permit exactly one reviewed first post');$_SESSION=['UserID'=>$uid,'Role'=>'Admin'];st(correction_control_integrity($p)===[],'Concurrent '.$kind.' leaves full dated/link reconciliation valid');
    }
    st(correction_integrity($p)===[],'Final fully migrated correction/evidence/advance integrity passes');[$code,$pre]=s3preflight('preflight_stage3.php',$db);st($code===0&&$pre['schema_complete']&&!$pre['writes_performed'],'Shared preflight accepts committed advance correction chains read-only');
    // Separate untouched browser fixtures; no working-system synthetic postings.
    $br=avrelease($p,$uid,$employeeId,$bank,$ctrl,'10000.00',cp4date(-5),cp4date(2));$bl=cp4liq($p,$uid,$br['advance_id'],$training,'8000.00',cp4date(-4));$bld=cp4draft($p,$uid,$bl['id'],journal_today(),'7000.00');$bld=cp4support($p,$uid,$bld);$bret=cp4return($p,$uid,$br['advance_id'],$bank,'2000.00',cp4date(-3));$brd=cp4draft($p,$uid,$bret['id'],journal_today(),'1500.00');$brd=cp4support($p,$uid,$brd);
    $brel=avrelease($p,$uid,$employeeId,$bank,$ctrl,'10000.00',cp4date(-5),cp4date(2));$bnew=cp4draft($p,$uid,$brel['id'],journal_today(),'9000.00');$browserRequest=cp3request($p,$uid,$bnew);
    file_put_contents($run.'/stage3-checkpoint4-fixture.json',workspace_json(['database'=>$db,'receipt_root'=>RECEIPT_UPLOAD_DIR,'release_draft'=>$bnew['id'],'release_target'=>$brel['id'],'release_request'=>$browserRequest,'liquidation_draft'=>$bld['id'],'liquidation_target'=>$bl['id'],'return_draft'=>$brd['id'],'return_target'=>$bret['id'],'blocked_release'=>$br['id'],'settlement_advance'=>$br['advance_id'],'posted_release_draft'=>$nd['id'],'replaced_advance'=>$old,'cancelled_advance'=>$history['advance_id'],'bank'=>$bank,'training'=>$training,'control'=>$ctrl,'employee'=>$employeeId]));
    echo "Stage 3 checkpoint 4 checks: $checks\nRegression checks: ".workspace_json($regression)."\nFixture: $run/stage3-checkpoint4-fixture.json\n";
}catch(Throwable $e){if($p->inTransaction())$p->rollBack();fwrite(STDERR,$e->getMessage()."\n".$e->getTraceAsString()."\n");exit(1);}
