"""Local-only U1-C prototype checks. Does not start PHP or connect to a database."""
import argparse
import hashlib
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / '.migration-private/journal-test-deps'))
from playwright.sync_api import sync_playwright

parser = argparse.ArgumentParser()
parser.add_argument('--output', default='.migration-private/u1c-revision-verification')
args = parser.parse_args()
OUT = (ROOT / args.output).resolve()
if not OUT.is_relative_to((ROOT / '.migration-private').resolve()):
    raise SystemExit('Results must stay under .migration-private.')
OUT.mkdir(parents=True, exist_ok=True)
IMAGES = ROOT / 'docs/images/usability-u1-prototype'
IMAGES.mkdir(parents=True, exist_ok=True)
HTML = ROOT / 'docs/prototypes/usability-u1-payment.html'
checks, shots, errors, requests, layout = [], [], [], [], []

def check(condition, name):
    if not condition:
        raise AssertionError(name)
    checks.append(name)

with sync_playwright() as pw:
    browser = pw.chromium.launch(executable_path='C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe', headless=True)
    context = browser.new_context(viewport={'width': 1366, 'height': 768})
    page = context.new_page()
    page.on('pageerror', lambda error: errors.append(str(error)))
    page.on('request', lambda request: requests.append(request.url))
    page.on('dialog', lambda dialog: dialog.accept())
    page.goto(HTML.as_uri())

    def snap():
        return page.evaluate('window.demoSnapshot()')

    def action(name):
        page.locator(f'[data-action="{name}"]').first.click()

    def tools():
        if not page.locator('#demo-tools').evaluate('(e)=>e.open'):
            page.locator('#demo-tools > summary').click()

    def example(name='filled'):
        tools()
        action('reset')
        tools()
        page.select_option('#scenario', name)
        action('load-example')

    def combo(select_id, query, keyboard=False):
        root = page.locator('#' + select_id).locator('..')
        field = root.locator('[role=combobox]')
        field.fill(query)
        if keyboard:
            field.press('ArrowDown')
            field.press('Enter')
        else:
            root.locator('[role=option]').first.click()

    def capture(name, size=(1366, 768), full=False):
        page.set_viewport_size({'width': size[0], 'height': size[1]})
        page.evaluate('window.scrollTo(0,0)')
        page.screenshot(path=str(IMAGES / name), full_page=full)
        shots.append(name)
        check(page.evaluate('document.documentElement.scrollWidth <= innerWidth'), name + ': no horizontal page overflow')

    def reviewed():
        action('review-again') if snap()['view'] == 'review' else page.locator('#review-button').click()
        page.wait_for_selector('#record-button')

    # Blank entry and honest validation state.
    action('start-dashboard')
    check(snap()['mode'] == 'quick', 'Blank entry starts in quick mode')
    check(page.locator('#entry-form input[data-bind="cash_amount"]').count() == 1, 'Quick form has one amount')
    capture('enter-empty-1366.png')
    page.locator('#review-button').click()
    page.wait_for_selector('#error-summary')
    check(snap()['recordCount'] == 0 and snap()['saved'] is not None, 'Invalid review saves draft without recording')
    check('needs correction' in page.locator('#draft-status').inner_text(), 'Validation status is saved but needs correction')
    check(page.evaluate('document.activeElement.id') == 'error-summary', 'Validation summary receives focus')
    capture('validation-1366.png')
    payee_control = page.locator('#payee').locator('..').locator('[role=combobox]')
    check(payee_control.get_attribute('aria-invalid') == 'true', 'Visible searchable payee exposes invalid state')
    check('field-error-payee' in payee_control.get_attribute('aria-describedby'), 'Visible payee associates its inline error')
    page.locator('[data-error-focus=payee]').click()
    check(payee_control.evaluate('(e)=>e === document.activeElement'), 'Summary link focuses visible payee rather than hidden select')
    payee_control.fill('not a committed selection')
    check(page.locator('#field-error-payee').is_visible(), 'Search query alone cannot clear required selection error')
    payee_control.press('Escape')
    page.fill('#purpose', 'Corrected purpose')
    check(page.locator('#field-error-purpose').count() == 0 and page.locator('#purpose').get_attribute('aria-invalid') is None, 'Corrected field clears only its own error and invalid association')
    check(page.locator('#field-error-payee').is_visible() and page.locator('#field-error-bank').is_visible(), 'Unrelated unresolved errors remain after purpose edit')
    page.fill('#purpose', '')
    check(page.locator('#field-error-purpose').is_visible(), 'A field becoming invalid again regains its error')
    combo('payee', 'training supplier', keyboard=True)
    check(page.locator('#field-error-payee').count() == 0 and page.locator('#field-error-bank').is_visible(), 'Selector commit clears only corrected error')
    check(snap()['view'] == 'enter' and snap()['recordCount'] == 0, 'Per-field validation never records or advances workflow')
    capture('validation-partially-corrected-1366.png', full=True)

    # Visible searchable controls; typing never commits a record ID.
    example('empty')
    original = snap()
    field = page.locator('#payee').locator('..').locator('[role=combobox]')
    field.fill('no-such-payee')
    check(page.get_by_text('No matching options', exact=True).is_visible(), 'No-match search has visible feedback')
    check(snap()['data'] == original['data'] and not snap()['dirty'], 'Search typing does not edit payload or dirty state')
    field.press('Escape')
    check(field.input_value() == 'Select a payee' and field.get_attribute('aria-expanded') == 'false', 'Escape restores committed placeholder')
    combo('payee', 'training supplier', keyboard=True)
    check(snap()['data']['payee'] == 'pty-demo', 'Keyboard commits eligible payee ID')
    check(snap()['view'] == 'enter' and snap()['saved'] is None, 'Enter in combobox does not submit payment')
    page.fill('#purpose', 'Training materials')
    page.fill('#cash-amount', 'not-an-amount')
    check(snap()['data']['lines'][0]['debit'] == 'not-an-amount', 'Invalid typed quick amount remains preserved on both sides')
    page.fill('#cash-amount', '1000.25')
    check(snap()['data']['lines'][0]['debit'] == '1000.25', 'Quick amount explicitly updates both journal sides')
    combo('bank', '100 bank')
    combo('counterpart', '510 materials')
    combo('project', 'training')
    check(snap()['data']['cash_project'] == snap()['data']['lines'][0]['project'] == 'p-training', 'Common project changes both authoritative line tags')
    check(snap()['mode'] == 'quick', 'Valid simple edits stay faithfully representable')
    field = page.locator('#project').locator('..').locator('[role=combobox]')
    before = snap()['data']
    field.fill('uncommitted query')
    field.press('Tab')
    check(snap()['data'] == before and field.input_value() == 'Demo Training Project', 'Tab cancels query and preserves IDs')
    combo('project', 'organization')
    check(snap()['data']['cash_project'] == '', 'Explicit Organization operations choice is retained')
    page.evaluate('window.scrollTo(0,0)')
    bounds = page.locator('#review-button').bounding_box()
    layout.append({'viewport': '1366x768', 'review_button_bottom': bounds['y'] + bounds['height']})
    check(bounds['y'] + bounds['height'] <= 768, 'Simple payment primary action fits laptop first viewport')
    capture('enter-filled-1366.png')
    capture('enter-filled-1920.png', (1920, 1080))
    page.set_viewport_size({'width': 1366, 'height': 768})

    # Saved versus later edits and leave handling.
    action('save')
    page.wait_for_function('() => !demoSnapshot().dirty && demoSnapshot().saved !== null')
    saved = snap()['saved']
    page.fill('#purpose', 'Changed but unsaved')
    check('Unsaved changes' in page.locator('#draft-status').inner_text(), 'Later edits replace saved status')
    action('back')
    check(page.locator('#leave-dialog').evaluate('(e)=>e.open'), 'Context Back guards unsaved edits')
    capture('unsaved-leave-1366.png')
    page.click('#stay')
    check(snap()['data']['purpose'] == 'Changed but unsaved', 'Stay preserves latest edits')
    action('back')
    page.keyboard.press('Escape')
    check(not page.locator('#leave-dialog').evaluate('(e)=>e.open') and snap()['dirty'], 'Escape cancels leave without saving')
    action('back')
    page.click('#leave-unsaved')
    check(snap()['view'] == 'dashboard' and snap()['saved'] == saved, 'Leave without latest edits preserves earlier saved draft')
    action('drafts')
    action('resume')
    check(snap()['data'] == saved, 'Resume restores acknowledged saved version')
    page.fill('#purpose', 'Saved on departure')
    tools()
    page.check('#save-fail')
    action('back')
    page.click('#save-leave')
    page.wait_for_selector('#leave-error:not([hidden])')
    check(snap()['view'] == 'enter' and snap()['dirty'] and snap()['data']['purpose'] == 'Saved on departure', 'Failed save-and-leave retains form and latest edits')
    page.click('#save-leave')
    page.wait_for_function('() => demoSnapshot().view === "dashboard"')
    check(snap()['saved']['purpose'] == 'Saved on departure', 'Successful save-and-leave acknowledges contents before leaving')

    # Previously missed routes: saved work survives a task start and current navigation is inert.
    acknowledged = snap()['saved']
    page.locator('[data-nav=payment]').click()
    check(snap()['data'] == acknowledged and snap()['saved'] == acknowledged, 'Payment start from another page resumes saved snapshot')
    before = snap()
    page.locator('[data-nav=payment]').click()
    check(snap() == before, 'Current payment navigation does not reset values, saved version or revision')
    page.fill('#purpose', 'Saved before switching to book')
    page.locator('[data-nav=cdb]').click()
    page.click('#save-leave')
    page.wait_for_function('() => demoSnapshot().view === "cdb"')
    acknowledged = snap()['saved']
    check(acknowledged['purpose'] == 'Saved before switching to book', 'Save-and-leave preserves snapshot when switching tasks')
    action('start-cdb')
    check(snap()['saved'] == acknowledged and snap()['data'] == acknowledged, 'Book Record a payment cannot erase just-saved draft')
    page.fill('#purpose', 'Latest edits to keep')
    before = snap()
    page.locator('[data-nav=payment]').click()
    check(snap() == before and not page.locator('#leave-dialog').evaluate('(e)=>e.open'), 'Clicking active task preserves even unsaved edits without reset prompt')
    page.locator('[data-nav=dashboard]').click()
    page.click('#leave-unsaved')
    action('start-dashboard')
    check(snap()['saved'] == acknowledged and snap()['data'] == acknowledged, 'Dashboard start preserves saved version after leaving without latest edits')
    action('back')
    action('drafts')
    capture('saved-draft-preserved-1366.png')
    action('resume')

    # Inline creation and required empty options.
    action('drafts')
    action('resume')
    action('add-payee')
    page.fill('#master-name', 'Demo new supplier')
    page.locator('#master-form button[type=submit]').click()
    check(snap()['data']['payee'].startswith('pty-created-'), 'Inline creation selects synthetic payee')
    check(page.locator('#payee').locator('..').locator('[role=combobox]').evaluate('(e)=>e === document.activeElement'), 'Inline creation restores selector focus')
    action('add-payee')
    page.click('#master-cancel')
    check(page.locator('#payee').locator('..').locator('[role=combobox]').evaluate('(e)=>e === document.activeElement'), 'Inline cancel restores selector focus')
    combo('bank', 'select cash')
    page.locator('#review-button').click()
    page.wait_for_selector('#error-summary')
    check(snap()['data']['cash_account'] == '' and snap()['recordCount'] == 0, 'Cleared required account fails validation without inferred selection')

    # Representation boundaries and preservation across mode switches.
    for name, expected in [('split', 'split'), ('mismatch', 'split'), ('projects', 'split'), ('withholding', 'advanced'), ('negative', 'advanced'), ('malformed', 'advanced')]:
        example(name)
        data = snap()['data']
        check(snap()['mode'] == expected, name + ': faithful automatic mode')
        action('quick')
        check(snap()['data'] == data and snap()['mode'] == expected, name + ': refused simplification leaves amounts, sides and projects intact')
        if name in ['negative', 'malformed']:
            check(page.input_value('#line-credit-0') == data['lines'][0]['credit'], name + ': opposite-side invalid input is visible')
            capture(name + '-1366.png', full=True)
            page.locator('#review-button').click()
            page.wait_for_selector('#error-summary')
            page.locator('[data-error-focus=line-debit-0]').click()
            check(page.evaluate('document.activeElement.id') == 'line-debit-0', name + ': detailed amount error link focuses its visible field')
            page.fill('#purpose', 'Changed purpose with invalid amount retained')
            check(page.locator('#line-credit-0').get_attribute('aria-invalid') == 'true' and page.input_value('#line-credit-0') == data['lines'][0]['credit'], name + ': unrelated edit retains invalid opposite-side value and error')
            action('drafts')
            page.click('#save-leave')
            page.wait_for_function('() => demoSnapshot().view === "drafts"')
            action('resume')
            check(page.locator('#line-credit-0').get_attribute('aria-invalid') == 'true', name + ': resumed saved invalid draft restores associated errors')
            page.fill('#line-credit-0', '0.00')
            check(page.locator('#line-credit-0').get_attribute('aria-invalid') is None and page.locator('#field-error-line-credit-0').count() == 0, name + ': correcting opposite side clears its error')
        if name == 'withholding':
            reviewed()
            breakdown = page.locator('[aria-label="Payment amount breakdown"]')
            check(breakdown.is_visible() and all(x in breakdown.inner_text() for x in ['4,500.00', '500.00', '4,000.00']), 'Withholding review groups gross costs, liability and cash above confirmation')
            check(breakdown.bounding_box()['y'] < page.locator('#record-button').bounding_box()['y'], 'Withholding relationship appears before final action')
            check('4,000' in page.locator('.summary-amount').inner_text(), 'Withholding review shows actual cash 4,000 separately from 4,500 cost and 500 liability')
            check(page.locator('table').inner_text().count('4,500.00') >= 1 and '500.00' in page.locator('table').inner_text(), 'Withholding full journal retains gross debit and liability credit')
            capture('withholding-review-1920.png', (1920, 1080), full=True)
            page.set_viewport_size({'width': 1366, 'height': 768})

    example()
    page.locator('#evidence-details > summary').click()
    page.select_option('#evidence-state', 'reviewed')
    data = snap()['data']
    action('advanced')
    check(snap()['data'] == data, 'Detailed view preserves client line IDs and document allocations')
    action('quick')
    check(snap()['data'] == data and snap()['mode'] == 'quick', 'Eligible quick view restores without financial mutation')
    action('add-line')
    check(len(snap()['data']['lines']) == 2 and snap()['data']['documents'] == data['documents'], 'Adding allocation retains existing line identity and evidence links')
    check(page.locator('#line-account-1').locator('..').locator('[role=combobox]').is_visible(), 'New allocation has visible searchable selector')
    example('unavailable')
    check('Unavailable selection' in page.locator('#counterpart').locator('..').inner_text(), 'Unavailable saved selection is visibly retained')
    field = page.locator('#counterpart').locator('..')
    field.locator('.combo-top button').click()
    check(field.locator('[role=option]').filter(has_text='old-unavailable').count() == 0, 'Unavailable record cannot be selected as eligible option')
    field.locator('[role=combobox]').press('Escape')
    example('long')
    field = page.locator('#payee').locator('..')
    field.locator('.combo-top button').click()
    check(field.locator('.combo-note').evaluate('(e)=>getComputedStyle(e).fontSize') == '13px', 'Full committed long-label text uses larger readable size')
    capture('long-labels-1366.png', full=True)
    field.locator('[role=combobox]').press('Escape')

    # Focused review, expiry, document checks, recording and exact access.
    example()
    page.locator('#evidence-details > summary').click()
    page.select_option('#evidence-state', 'unreviewed')
    page.locator('#review-button').click()
    page.wait_for_selector('#error-summary')
    check('Review the attached demo document' in page.locator('#error-summary').inner_text(), 'Unreviewed attachment blocks recording')
    page.locator('#evidence-details > summary').click()
    page.locator('[data-error-focus=evidence-state]').click()
    check(page.locator('#evidence-details').evaluate('(e)=>e.open') and page.evaluate('document.activeElement.id') == 'evidence-state', 'Summary link opens hidden document group and focuses associated control')
    page.select_option('#evidence-state', 'reviewed')
    reviewed()
    before = snap()
    page.locator('[data-nav=payment]').click()
    check(snap() == before and page.locator('#record-button').is_visible(), 'Active payment navigation preserves focused review and token')
    check(snap()['recordCount'] == 0 and page.locator('#entry-form').count() == 0, 'Review is a distinct view and does not record')
    check('800.00' in page.locator('#app').inner_text() and '1,000.00' in page.locator('#app').inner_text(), 'Ordinary partial support is truthfully displayed')
    capture('review-1366.png')
    page.evaluate('window.scrollTo(0,0)')
    bounds = page.locator('#record-button').bounding_box()
    layout.append({'viewport': '1366x768', 'confirm_button_bottom': bounds['y'] + bounds['height']})
    check(bounds['y'] + bounds['height'] <= 768, 'Simple review confirmation fits laptop first viewport')
    capture('review-1920.png', (1920, 1080))
    page.set_viewport_size({'width': 1366, 'height': 768})
    action('edit')
    check(not snap()['dirty'], 'Back to editing alone does not make saved values unsaved')
    field = page.locator('#payee').locator('..').locator('[role=combobox]')
    before = snap()
    field.fill('query only')
    field.press('Escape')
    check(snap()['revision'] == before['revision'] and snap()['data'] == before['data'] and not snap()['dirty'], 'Selector cancellation keeps saved financial state')
    reviewed()
    tools()
    action('expire')
    check(page.locator('#record-button').count() == 0 and snap()['recordCount'] == 0, 'Expired review cannot record')
    reviewed()
    page.locator('#record-button').dblclick()
    page.wait_for_function('() => demoSnapshot().view === "recorded"')
    check(snap()['recordCount'] == snap()['postCalls'] == 1, 'Rapid repeat record produces one simulated result')
    check(page.locator('#entry-form').count() == 0 and page.locator('#draft-status').count() == 0, 'Recorded view removes editable form and stale draft status')
    check(snap()['saved'] is None, 'Posted draft no longer appears as an editable saved draft')
    capture('recorded-1366.png')
    capture('recorded-1920.png', (1920, 1080))
    action('detail')
    check(snap()['view'] == 'detail' and 'J-DEMO-001' in page.locator('#app').inner_text(), 'Exact result link opens the recorded identity')
    check(page.locator('#app input:not(#demo-tools input), #app textarea').count() == 0, 'Exact record has no editable financial controls')
    capture('exact-record-1920.png', (1920, 1080))
    action('recorded')
    action('cdb')
    check('all dates' in page.locator('#app').inner_text() and page.locator('tbody tr').count() == 1, 'CDB opens a list across all demo dates')
    action('open-record')
    check(snap()['result']['id'] == 'J-DEMO-001', 'Book row opens exact recorded snapshot')
    page.locator('[data-nav=history]').click()
    check('all dates' in page.locator('#app').inner_text(), 'Journal History remains a separate list')
    page.locator('[data-nav=drafts]').click()
    check(page.locator('[data-action=resume]').count() == 0, 'My drafts does not resume recorded payment for editing')

    # Definitive rejection and uncertain response use different states.
    example()
    reviewed()
    tools()
    page.select_option('#response-mode', 'rejected')
    action('record')
    page.wait_for_selector('#error-summary')
    check(snap()['recordCount'] == 0 and snap()['saved'] is not None, 'Definitive recording rejection preserves saved values without a result')
    example()
    reviewed()
    tools()
    page.select_option('#response-mode', 'uncertain')
    page.check('#recovery-fail')
    action('record')
    page.wait_for_function('() => demoSnapshot().view === "uncertain"')
    key = snap()['postKey']
    check(snap()['recordCount'] == 1 and snap()['postCalls'] == 1, 'Lost response may have one committed simulated payment')
    check(page.locator('.sidebar button:enabled').count() == 0 and page.locator('#entry-form').count() == 0, 'Uncertain state pauses editing and navigation')
    capture('uncertain-1366.png')
    action('recover')
    page.wait_for_function('() => demoSnapshot().recoveryCalls === 1')
    check(snap()['view'] == 'uncertain' and snap()['postKey'] == key, 'Failed result check keeps the same recovery identity')
    tools()
    action('expire')
    action('recover')
    page.wait_for_function('() => demoSnapshot().view === "recorded"')
    check(snap()['postKey'] == key and snap()['recordCount'] == snap()['postCalls'] == 1 and snap()['result']['recovered'], 'Recovery returns original result without re-recording or new review')
    capture('recovered-1366.png')
    example('empty')
    action('back')
    page.locator('[data-nav=cdb]').click()
    action('start-cdb')
    check('Back to Cash Disbursements Book' in page.locator('.context-links').inner_text(), 'Book entry names its contextual Back destination')
    action('back')
    check(snap()['view'] == 'cdb', 'Contextual Back opens local book without any production navigation')

    # Safety checks and immutable production-source preservation.
    check(not errors, 'No browser JavaScript errors')
    check(all(url.startswith('file:') for url in requests), 'No network requests or production routes accessed')
    check(page.evaluate('document.querySelectorAll("script[src],link[href],iframe,form[action]").length') == 0, 'No external assets, embeds or backend form actions')
    manifest = json.loads((ROOT / '.migration-private/u1a-capture-51c1dac86b/source-manifest.json').read_text(encoding='utf-8-sig'))
    files = manifest['files']
    check(all(hashlib.sha256((ROOT / path).read_bytes()).hexdigest() == digest for path, digest in files.items()), f'All {len(files)} captured application files unchanged')
    result = {'passed': len(checks), 'checks': checks, 'browser': browser.version, 'engine': 'headless Microsoft Edge', 'prototype_sha256': hashlib.sha256(HTML.read_bytes()).hexdigest(), 'screenshots': {name: hashlib.sha256((IMAGES / name).read_bytes()).hexdigest() for name in shots}, 'layout': layout, 'application_files_preserved': len(files), 'network_requests': [u for u in requests if not u.startswith('file:')], 'errors': errors}
    (OUT / 'results.json').write_text(json.dumps(result, indent=2), encoding='utf-8')
    print(json.dumps({k: result[k] for k in ['passed', 'browser', 'prototype_sha256', 'application_files_preserved', 'layout']}, indent=2))
    context.close()
    browser.close()
