<?php
require_once __DIR__.'/accounting_workspace.php';require_once __DIR__.'/layout.php';
if($_SERVER['REQUEST_METHOD']!=='GET'){header('Allow: GET');http_response_code(405);exit;}
header('Cache-Control: private, no-store');
try{workspace_guard($pdo,(int)$_SESSION['UserID']);$lists=workspace_lists($pdo,(int)$_SESSION['UserID']);}
catch(JournalProblem $e){http_response_code($e->status);exit(htmlspecialchars($e->getMessage(),ENT_QUOTES,'UTF-8'));}
$advanceMode=$advanceConfig['workflow_kind']??null;
$ordinaryPayment=$workspaceBook==='CDB'&&$advanceMode===null&&!isset($correctionConfig);
$isCorrection=isset($correctionConfig);$reverseOnly=$isCorrection&&$correctionConfig['mode']==='reverse_only';
$title=$advanceMode!==null?['advance_release'=>'Release cash advance','advance_liquidation'=>'Liquidate cash advance','advance_return'=>'Return unused cash'][$advanceMode]:['CRB'=>'New cash receipt','CDB'=>'New cash payment','GJ'=>'New journal entry'][$workspaceBook];
$esc=fn($v)=>htmlspecialchars((string)$v,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');
if($isCorrection)$title=$reverseOnly?'Prepare journal reversal':'Prepare journal correction';
if($ordinaryPayment)$title='Record a payment';
layout_begin($title,$ordinaryPayment?'payment':['CRB'=>'crb','CDB'=>'cdb','GJ'=>'general_journal'][$workspaceBook],[], '<link rel="stylesheet" href="assets/css/accounting_workspace.css?v='.filemtime(__DIR__.'/../assets/css/accounting_workspace.css').'">');
?>
<div class="accounting-workspace <?= $ordinaryPayment?'aw-payment':'' ?> <?= $reverseOnly?'aw-reverse-only':'' ?>" id="entry-workspace">
<header class="aw-header"><div><p class="aw-eyebrow">DAILY ACCOUNTING · <?= $workspaceBook ?></p><h1><?= $title ?></h1><p><?= $ordinaryPayment?'Enter the payment details, review, then confirm to record.':'Prepare an entry, save your draft, then review the complete debit and credit posting.' ?></p></div><div><a href="accounting_drafts.php">My drafts</a><?php if($isCorrection): ?> &middot; <button type="button" class="aw-no-print" onclick="window.print()">Print comparison</button><?php endif; ?><?php if($advanceMode): ?> &middot; <a href="cash_advances.php">Advance register</a> &middot; <button type="button" onclick="window.print()">Print draft</button><?php endif; ?></div></header>
<?php if($isCorrection&&!$advanceMode): ?><p id="aw-print-label" class="aw-print-label">DRAFT &mdash; not a posted financial record</p><?php endif; ?><?php if($advanceMode): ?><p id="aw-print-label" class="aw-print-label">DRAFT &mdash; not a posted financial record</p><section class="aw-card" id="aw-advance-context" aria-live="polite"></section><?php endif; ?>
<?php if($ordinaryPayment): ?><a class="aw-context-back" href="financial_records.php?view=cdb&amp;from=&amp;to=">Back to payments book</a><ol id="aw-progress" aria-label="Payment progress"><li aria-current="step">1 Enter details</li><li>2 Review</li><li>3 Recorded</li></ol><p id="aw-mode-notice"></p><?php endif; ?>
<p id="aw-status" role="status" aria-live="polite"></p><p id="aw-error" role="alert" tabindex="-1"></p>
<?php if($isCorrection): ?><section class="aw-card" id="aw-correction-context"><h2>Original journal #<?= $esc($correctionConfig['target_journal_id']) ?></h2><div id="aw-original"></div><p id="aw-correction-eligibility" role="status"></p><div class="aw-grid"><label>Correction mode<select id="aw-correction-mode" <?= $draftId!==null?'disabled':'' ?>><option value="reverse_replace" <?= !$reverseOnly?'selected':'' ?>>Reverse and replace</option><option value="reverse_only" <?= $reverseOnly?'selected':'' ?>>Reverse only</option></select></label><?php if(!$advanceMode&&!$reverseOnly): ?><label>Replacement book<select id="aw-replacement-book"><option value="CRB" <?= $workspaceBook==='CRB'?'selected':'' ?>>Cash Receipts Book</option><option value="CDB" <?= $workspaceBook==='CDB'?'selected':'' ?>>Cash Disbursements Book</option><option value="GJ" <?= $workspaceBook==='GJ'?'selected':'' ?>>General Journal</option></select></label><?php endif; ?></div><p>Original records remain unchanged. The generated reversal goes to General Journal. Drafts and previews do not change financial records.</p></section><?php endif; ?>
<div class="aw-columns"><form id="aw-entry" novalidate class="aw-card">
<?php if($ordinaryPayment): ?><div class="aw-payment-modes" aria-label="Entry presentation"><button type="button" data-payment-mode="quick">Quick form</button><button type="button" data-payment-mode="split">Split allocations</button><button type="button" data-payment-mode="advanced">Advanced journal</button></div><?php endif; ?><h2>Transaction details <span id="aw-draft-label">Unsaved draft</span></h2>
<div class="aw-grid"><label>Date<input id="aw-date" type="date" value="<?= journal_today() ?>" min="1000-01-01" <?= ($workspaceBook!=='GJ'||$advanceMode)?'max="'.journal_today().'"':'' ?>></label>
<?php if($isCorrection): ?><label class="aw-correction-field">Correction reason<textarea id="aw-correction-reason" maxlength="2000" rows="2"></textarea></label><label class="aw-correction-field">Earlier-date explanation<textarea id="aw-backdate-reason" maxlength="2000" rows="2"></textarea></label><?php endif; ?>
<label <?= $reverseOnly?'hidden':'' ?>>Reference <small>Optional</small><input id="aw-reference" maxlength="100" placeholder="Voucher, bank or receipt reference"></label>
<label><?= $advanceMode?'Accountable employee':($workspaceBook==='CRB'?'Payer':($workspaceBook==='CDB'?'Payee':'Party (optional)')) ?><select id="aw-party"></select><button type="button" data-new-master="parties">+ Add party</button></label>
<label>Default project<select id="aw-default-project"></select><button type="button" id="aw-apply-project">Apply to all lines</button><button type="button" data-new-master="projects">+ Add project</button></label></div>
<?php if($advanceMode==='advance_release'): ?><div class="aw-grid"><label>Advance control account<select id="aw-control-account"></select></label><label>Liquidation due date<input type="date" id="aw-due-date" min="1000-01-01"></label></div><details><summary>External approval recorded by accounting staff (optional)</summary><div class="aw-grid"><label>Approver name<input id="aw-approval-name" maxlength="100"></label><label>Approval date<input id="aw-approval-date" type="date"></label><label>Approval reference<input id="aw-approval-reference" maxlength="100"></label></div></details><?php endif; ?>
<label>Purpose<textarea id="aw-purpose" rows="2" maxlength="2000" placeholder="Explain this transaction"></textarea></label>
<?php if($workspaceBook!=='GJ'): ?>
<div class="aw-cash"><div class="aw-grid"><label><?= $workspaceBook==='CRB'?'Receive into':'Pay from' ?><select id="aw-cash-account"></select></label><label>Actual cash/bank amount (PHP)<input id="aw-cash-amount" inputmode="decimal" placeholder="0.00"></label><label>Cash line project<select id="aw-cash-project"></select></label></div></div>
<?php else: ?><label <?= $advanceMode?'hidden':'' ?>>Entry kind<select id="aw-kind"><option value="ordinary">General journal</option><option value="transfer">Internal cash transfer</option></select></label><?php endif; ?>
<div <?= $advanceMode&&$advanceMode!=='advance_liquidation'?'hidden':'' ?> class="aw-section-heading"><h2><?= $workspaceBook==='CRB'?'Receipt allocations':($workspaceBook==='CDB'?'Payment allocations':'Journal lines') ?></h2><div><?php if($workspaceBook!=='GJ'): ?><label class="aw-inline"><input type="checkbox" id="aw-advanced"> Advanced debit/credit entry</label><?php endif; ?><button type="button" id="aw-add-line">+ Add line</button></div></div>
<p <?= $advanceMode&&$advanceMode!=='advance_liquidation'?'hidden':'' ?> class="aw-help">Line projects determine project activity. Organization operations has no project tag.</p>
<div id="aw-lines"></div><div class="aw-totals" aria-live="polite"><span>Debit <strong id="aw-debits">₱0.00</strong></span><span>Credit <strong id="aw-credits">₱0.00</strong></span><span>Difference <strong id="aw-difference">₱0.00</strong></span></div>
<div class="aw-actions"><button type="button" id="aw-save">Save draft</button><button type="submit" class="aw-primary" id="aw-review">Review entry</button></div>
</form>
<aside class="aw-card"><h2>Supporting documents</h2><p class="aw-help"><?= $advanceMode==='advance_liquidation'?'Fully support every expenditure or asset debit.':($advanceMode==='advance_return'?'Attach and review proof of the cash return.':($advanceMode?'Release proof is optional.':'Optional for ordinary entries.')) ?> Attached images must be manually reviewed. Photos remain private; uploading does not run OCR.</p>
<label class="aw-upload">Add image (JPG, PNG, WebP; up to 8 MB)<input type="file" id="aw-upload" accept="image/jpeg,image/png,image/webp"></label>
<button type="button" id="aw-upload-retry" hidden>Retry interrupted upload</button>
<div class="aw-grid"><label>Existing unposted image<select id="aw-existing"></select></label><button type="button" id="aw-attach">Attach selected</button></div>
<?php if($advanceMode==='advance_liquidation'): ?><p class="aw-document-warning" id="aw-liquidation-reuse-warning">Once an image is posted, its unused or excluded amount cannot support another liquidation. Use distinct documents for separate liquidations.</p><?php endif; ?>
<div id="aw-documents"></div><?php if($advanceMode==='advance_return'): ?><p id="aw-proof-status" role="status"></p><button type="button" id="aw-confirm-proof">Confirm return proof</button><?php endif; ?><p class="aw-help" id="aw-evidence-help"><?= $advanceMode==='advance_liquidation'?'Monetary evidence must fully cover every expenditure or eligible asset debit. Informational documents and the advance-control credit do not add expenditure coverage.':($advanceMode==='advance_return'?'Reviewed informational proof and confirmation are required for this return. Monetary evidence allocations are not used.':($advanceMode?'Reviewed informational release proof is optional. Monetary evidence allocations are not used.':'Monetary support covers noncash allocations. Informational documents do not add monetary coverage. Missing or partial support will be shown at review.')) ?></p></aside></div>
<?php if($isCorrection&&!$reverseOnly): ?><section class="aw-card" id="aw-reuse-card"><h2>Reuse an original image</h2><p>The prior review is a reference. Review the image again and explain any changed purpose or amounts.</p><div class="aw-grid"><label>Eligible target image<select id="aw-reuse"></select></label><button type="button" id="aw-attach-reuse">Attach target image</button></div></section><?php endif; ?>
<section class="aw-card" id="aw-review-panel" hidden><h2><?= $ordinaryPayment?'Review payment':'Review before posting' ?></h2><p><?= $ordinaryPayment?'Not recorded yet. Check these details before confirming. This review is not Management approval.':'This checks the accounting entry. It does not record management approval.' ?></p><div id="aw-review-content"></div><div class="aw-actions"><button type="button" id="aw-back">Back to editing</button><button type="button" class="aw-primary" id="aw-post"><?= $ordinaryPayment?'Confirm and record payment':'Post' ?> <?= $ordinaryPayment?'':($workspaceBook==='CRB'?'receipt':($workspaceBook==='CDB'?'payment':'journal')) ?></button></div></section>
<section class="aw-card" id="aw-posted" hidden><h2><?= $ordinaryPayment?'Payment recorded':'Entry posted' ?></h2><?php if($ordinaryPayment): ?><p>Finished. This payment is now in the accounting records.</p><a id="aw-exact-link" class="aw-record-link">View this transaction</a><?php endif; ?><?php if($advanceMode): ?><span id="aw-advance-navigation"><a id="aw-advance-link" href="cash_advances.php">View advance</a> &middot; </span><?php endif; ?><p id="aw-posted-message"></p><?php if($workspaceBook!=='GJ'): ?><a id="aw-posted-link" href="financial_records.php?view=<?= strtolower($workspaceBook) ?>&amp;from=&amp;to=">View <?= $workspaceBook==='CRB'?'Cash Receipts Book':'Cash Disbursements Book' ?></a> · <?php endif; ?><a id="aw-history-link" href="financial_records.php?from=&amp;to=">View Journal History</a> · <a href="<?= $advanceMode?'cash_advance_entry.php?workflow_kind=advance_release':['CRB'=>'cash_receipt.php','CDB'=>'cash_disbursement.php','GJ'=>'general_journal.php'][$workspaceBook] ?>">Prepare another entry</a></section>
<?php if($ordinaryPayment): ?><section class="aw-card" id="aw-unknown" hidden><h2>Check recording result</h2><p>The response was interrupted. The payment may already be recorded. Check the same request before editing or starting another payment.</p><button type="button" id="aw-check-result" class="aw-primary">Check recording result</button></section><dialog id="aw-leave-dialog"><h2>Leave with unsaved changes?</h2><p>Your last saved draft remains available. The latest edits have not been saved.</p><p id="aw-leave-error" role="alert"></p><div class="aw-actions"><button type="button" id="aw-leave-stay">Stay</button><button type="button" id="aw-leave-unsaved">Leave without latest edits</button><button type="button" id="aw-leave-save" class="aw-primary">Save draft and leave</button></div></dialog><?php endif; ?>
<dialog id="aw-master-dialog"><form id="aw-master-form"><h2 id="aw-master-title">New master</h2><label>Name<input name="name" required maxlength="100"></label><label id="aw-master-code-label">Project code<input name="code" maxlength="30"></label><label id="aw-master-type-label">Party type<select name="party_type"><option value="person">Person</option><option value="organization">Organization</option></select></label><label>Description (optional)<textarea name="description" maxlength="2000"></textarea></label><p id="aw-master-error" role="alert"></p><div class="aw-actions"><button type="button" id="aw-master-cancel">Cancel</button><button class="aw-primary">Create and select</button></div></form></dialog>
</div>
<script type="application/json" id="workspace-data"><?= json_encode(($correctionConfig??[])+($advanceConfig??[])+['ordinary_payment'=>$ordinaryPayment,'book'=>$workspaceBook,'csrf_token'=>csrf_token(),'lists'=>$lists,'draft_id'=>is_string($_GET['draft_id']??null)?$_GET['draft_id']:'','receipt_id'=>is_string($_GET['receipt_id']??null)?$_GET['receipt_id']:''],JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_QUOT|JSON_HEX_APOS|JSON_HEX_QUOT|JSON_THROW_ON_ERROR) ?></script>
<?php layout_end(($ordinaryPayment?'<script src="assets/js/payment_presentation.js?v='.filemtime(__DIR__.'/../assets/js/payment_presentation.js').'"></script>':'').'<script src="assets/js/accounting_workspace.js?v='.filemtime(__DIR__.'/../assets/js/accounting_workspace.js').'"></script>'); ?>
