<?php
/** Dedicated advance workflow. The shared journal writer runs inside our coordinated transaction. */
require_once __DIR__.'/accounting_workspace.php';
require_once __DIR__.'/accounting_query.php';

function advance_guard(PDO $pdo,int $uid,?array $request=null,bool $write=false): string
{
    if($uid<=0||(int)($_SESSION['UserID']??0)!==$uid)throw new JournalProblem('Please sign in again.',401);
    $s=$pdo->prepare('SELECT Role,Is_Active FROM Users WHERE UserID=?');$s->execute([$uid]);$u=$s->fetch();
    if(!$u||(int)$u['Is_Active']!==1||!in_array($u['Role'],['Admin','Management'],true)||($write&&$u['Role']!=='Admin'))throw new JournalProblem('You do not have permission for this advance action.',403);
    if(!stage2_enabled($pdo))throw new JournalProblem('Cash advances are not enabled. Complete Stage 2 deployment first.',503);
    if($request!==null&&!csrf_verify(is_string($request['csrf_token']??null)?$request['csrf_token']:null))throw new JournalProblem('Your session expired. Reload and try again.',400);
    return $u['Role'];
}
function advance_draft(array $d): void
{
    if((int)$d['payload_version']!==3||!in_array($d['workflow_kind'],['advance_release','advance_liquidation','advance_return'],true))throw new JournalProblem('Use the ordinary accounting workspace for this draft.',409);
}
function advance_number(int $id): string {return 'CA-'.str_pad((string)$id,10,'0',STR_PAD_LEFT);}
function advance_date(string $date,bool $future=false): string
{
    try{accounting_date($date);}catch(InvalidArgumentException $e){throw new JournalProblem('Choose a real accounting date from 1000-01-01 through 9998-12-31.',400);}
    if(!$future&&$date>journal_today())throw new JournalProblem('Advance accounting and reporting dates cannot be in the future.',400);
    return $date;
}
function advance_load(PDO $pdo,int $id,bool $lock=false): array
{
    $s=$pdo->prepare('SELECT a.*,j.entry_date release_date FROM cash_advances a JOIN journal_entries j ON j.id=a.release_journal_id WHERE a.id=?'.($lock?' FOR UPDATE':''));$s->execute([$id]);
    $a=$s->fetch();if(!$a)throw new JournalProblem('Cash advance not found.',404);return $a;
}
function advance_payload(array $p): array
{
    $out=workspace_payload($p);$out['transaction_kind']='ordinary';
    foreach(['control_account_id'=>10,'due_date'=>10,'approval_name'=>100,'approval_date'=>10,'approval_reference'=>100] as $k=>$limit){$v=journal_string($p,$k,true);if(mb_strlen($v)>$limit)throw new JournalProblem('Advance field exceeds its length limit.');$out[$k]=$v;}
    $notes=$p['line_notes']??[];if(!is_array($notes))throw new JournalProblem('Invalid allocation notes.');$out['line_notes']=[];
    foreach($out['lines'] as $l){if(in_array($l['client_id'],['control','cash'],true))throw new JournalProblem('Control lines are generated by the server.');$v=journal_string($notes,$l['client_id'],true);if(mb_strlen($v)>2000)throw new JournalProblem('Allocation note is too long.');$out['line_notes'][$l['client_id']]=$v;}
    return $out;
}
function advance_save(PDO $pdo,int $uid,array $r): array
{
    advance_guard($pdo,$uid,$r,true);$kind=journal_string($r,'workflow_kind');$books=['advance_release'=>'CDB','advance_liquidation'=>'GJ','advance_return'=>'CRB'];
    if(!isset($books[$kind]))throw new JournalProblem('Choose a valid advance operation.');$book=$books[$kind];
    $target=journal_id(journal_string($r,'advance_id',true),true);if(($kind==='advance_release')!==($target===null))throw new JournalProblem('Select the linked advance for settlement; releases create a new advance.');
    $p=advance_payload($r['payload']??[]);$key=journal_string($r,'submission_key');if(!preg_match('/\A[a-f0-9]{64}\z/',$key))throw new JournalProblem('Invalid durable submission key.');
    $id=journal_id(journal_string($r,'draft_id',true),true);$hash=hash('sha256',workspace_json([$kind,$target,$p]));
    return workspace_tx($pdo,$uid,function()use($pdo,$uid,$r,$kind,$book,$target,$p,$key,$id,$hash){
        if($id===null){
            if($p['documents'])throw new JournalProblem('Save the draft before attaching documents.');
            $s=$pdo->prepare('SELECT id,owner_id,creation_hash FROM journal_drafts WHERE submission_key=?');$s->execute([$key]);
            if($old=$s->fetch()){if((int)$old['owner_id']!==$uid||!hash_equals($old['creation_hash'],$hash))throw new JournalProblem('Draft creation key was used with different contents.',409);$d=workspace_draft($pdo,$uid,(int)$old['id']);advance_draft($d);return workspace_draft_public($d);}
            if($target!==null)advance_load($pdo,$target,true);
            $s=$pdo->prepare('INSERT INTO journal_drafts(owner_id,source_book,payload_version,payload,creation_hash,submission_key,workflow_kind,advance_id,created_at,updated_at) VALUES(?,?,3,?,?,?,?,?,UTC_TIMESTAMP(),UTC_TIMESTAMP())');
            $s->execute([$uid,$book,workspace_json($p),$hash,$key,$kind,$target]);$id=(int)$pdo->lastInsertId();
            workspace_audit($pdo,$uid,AUDIT_ACTION_CREATE,'Advance Draft',$id,null,['workflow_kind'=>$kind,'advance_id'=>$target]);
        }else{
            $d=workspace_draft($pdo,$uid,$id,true);advance_draft($d);workspace_revision($d,$r);
            if($d['submission_key']!==$key||$d['workflow_kind']!==$kind||($d['advance_id']===null?null:(int)$d['advance_id'])!==$target)throw new JournalProblem('Advance draft identity cannot change.',409);
            if(workspace_document_ids($p)!==workspace_document_ids($d['payload']))throw new JournalProblem('Use attach/remove to change document reservations.',409);
            // Retain confirmation only when its complete canonical proof context is unchanged.
            $confirmation=$d['return_confirmation'];
            if($confirmation!==null){try{if(advance_proof_context($pdo,$d,$p)!==advance_proof_context($pdo,$d,$d['payload']))$confirmation=null;}catch(JournalProblem $e){$confirmation=null;}}
            $pdo->prepare('UPDATE journal_drafts SET payload=?,return_confirmation=?,revision=revision+1,updated_at=UTC_TIMESTAMP() WHERE id=?')->execute([workspace_json($p),$confirmation,$id]);
            workspace_audit($pdo,$uid,AUDIT_ACTION_EDIT,'Advance Draft',$id,['revision'=>$d['revision']],['revision'=>(int)$d['revision']+1]);
        }return workspace_draft_public(workspace_draft($pdo,$uid,$id));
    });
}
function advance_canonical(PDO $pdo,array $d,array $payload,?array $original=null): array
{
    advance_draft($d);$p=advance_payload($payload);$kind=$d['workflow_kind'];$project=journal_id($p['default_project_id'],true);$party=journal_id($p['party_id'],true);$approval=null;$due=null;
    if($kind!=='advance_release'){$original=$original??advance_load($pdo,(int)$d['advance_id']);$party=(int)$original['party_id'];$project=$original['originating_project_id']===null?null:(int)$original['originating_project_id'];$control=(int)$original['control_account_id'];if($p['control_account_id']!==''&&journal_id($p['control_account_id'])!==$control)throw new JournalProblem('Settlement cannot change the original control account.',409);if($p['party_id']!==''&&journal_id($p['party_id'])!==$party)throw new JournalProblem('Settlement cannot change the original employee.',409);}
    else{$control=journal_id($p['control_account_id']);if($party===null)throw new JournalProblem('Choose the accountable employee.');$due=advance_date($p['due_date'],true);
        if($p['approval_name']!==''||$p['approval_date']!==''||$p['approval_reference']!==''){if($p['approval_name']===''||$p['approval_date']==='')throw new JournalProblem('External approval needs both approver name and date.');$approval=['name'=>$p['approval_name'],'date'=>advance_date($p['approval_date'],true),'reference'=>$p['approval_reference']];}}
    $projectString=$project===null?'':(string)$project;$raw=[];$ids=[];$gross=$liability=0;
    if($kind==='advance_liquidation'){
        $raw=$p['lines'];$ids=array_column($raw,'client_id');foreach($raw as $l){$gross+=journal_amount($l['debit_amount']);$liability+=journal_amount($l['credit_amount']);}
        $reduction=$gross-$liability;if($reduction<=0)throw new JournalProblem('Expenditure debits minus liability credits must be positive.');
        $raw[]=['account_id'=>(string)$control,'fund_project_id'=>$projectString,'debit_amount'=>'','credit_amount'=>ledger_decimal($reduction)];$ids[]='control';
    }else{
        if($p['lines'])throw new JournalProblem('Release and return lines are generated, not editable.');
        $reduction=journal_amount($p['cash_amount']);if($reduction<=0)throw new JournalProblem('Enter a positive cash amount.');
        $cash=['account_id'=>$p['cash_account_id'],'fund_project_id'=>$projectString,'debit_amount'=>$kind==='advance_return'?ledger_decimal($reduction):'','credit_amount'=>$kind==='advance_release'?ledger_decimal($reduction):''];
        $ctrl=['account_id'=>(string)$control,'fund_project_id'=>$projectString,'debit_amount'=>$kind==='advance_release'?ledger_decimal($reduction):'','credit_amount'=>$kind==='advance_return'?ledger_decimal($reduction):''];$raw=[$cash,$ctrl];$ids=['cash','control'];
    }
    $input=journal_input(['entry_date'=>$p['entry_date'],'reference'=>$p['reference'],'description'=>$p['description'],'lines'=>$raw,'line_count'=>(string)count($raw),'form_complete'=>'1']);
    foreach($input['lines'] as $i=>&$l)$l['client_id']=$ids[$i];unset($l);
    $documents=workspace_canonical_documents($p['documents']);
    return $input+['source_book'=>$d['source_book'],'transaction_kind'=>$kind,'party_id'=>$party,'documents'=>$documents,
        'advance_context'=>['advance_id'=>$kind==='advance_release'?null:(int)$d['advance_id'],'control_account_id'=>$control,'originating_project_id'=>$project,'due_date'=>$due,'approval'=>$approval,'line_notes'=>$p['line_notes'],'gross_costs'=>ledger_decimal($gross),'liability_credits'=>ledger_decimal($liability),'reduction'=>ledger_decimal($reduction)],
        'return_confirmation'=>$kind==='advance_return'&&$d['return_confirmation']!==null?json_decode($d['return_confirmation'],true,64,JSON_THROW_ON_ERROR):null];
}

/** Unfiltered, bidirectional reconciliation. Call within a repeatable read or the writer barrier. */
function advance_state(PDO $pdo,string $asof): array
{
    $rows=$pdo->query('SELECT a.*,j.entry_date release_date FROM cash_advances a JOIN journal_entries j ON j.id=a.release_journal_id ORDER BY a.id')->fetchAll();$advances=[];$reconciliation=[];
    foreach($pdo->query('SELECT d.account_id,c.Name account_name FROM advance_control_designations d JOIN Categories c ON c.CategoryID=d.account_id')->fetchAll() as $c)$reconciliation[(int)$c['account_id']]=['account_id'=>(int)$c['account_id'],'account_name'=>$c['account_name'],'register_cents'=>0,'ledger_cents'=>0,'errors'=>[]];
    foreach($rows as $a){$a['released_cents']=$a['liquidated_cents']=$a['returned_cents']=0;$a['operations']=[];$a['release_count']=0;$a['due_date']=$a['initial_due_date'];$advances[(int)$a['id']]=$a;}
    $ops=$pdo->query('SELECT o.*,j.entry_date,j.status,j.source_book,j.transaction_kind,l.journal_entry_id line_journal,l.account_id,l.debit_amount,l.credit_amount,d.workflow_kind,d.advance_id draft_advance,d.state draft_state,d.posted_journal_id FROM cash_advance_operations o LEFT JOIN journal_entries j ON j.id=o.journal_id LEFT JOIN journal_entry_lines l ON l.id=o.control_line_id LEFT JOIN journal_drafts d ON d.id=o.draft_id ORDER BY o.id')->fetchAll();$linked=[];
    foreach($ops as $o){$a=&$advances[(int)$o['advance_id']];$account=(int)$a['control_account_id'];$kind=$o['operation_kind'];$book=['release'=>'CDB','liquidation'=>'GJ','return'=>'CRB'][$kind];$debit=ledger_cents($o['debit_amount']??'0.00');$credit=ledger_cents($o['credit_amount']??'0.00');
        $valid=$o['status']==='posted'&&$o['source_book']===$book&&$o['transaction_kind']==='advance_'.$kind&&$o['workflow_kind']==='advance_'.$kind&&$o['draft_state']==='Posted'&&(int)$o['posted_journal_id']===(int)$o['journal_id']&&(int)$o['draft_advance']===(int)$a['id']&&(int)$o['line_journal']===(int)$o['journal_id']&&(int)$o['account_id']===$account&&($kind==='release'?($debit>0&&$credit===0&&(int)$a['release_journal_id']===(int)$o['journal_id']):($credit>0&&$debit===0&&$o['entry_date']>=$a['release_date']));
        if($o['entry_date']===null||$o['entry_date']<=$asof){if(!$valid)$reconciliation[$account]['errors'][]='Invalid operation #'.$o['id'];$linked[(int)$o['control_line_id']]=$valid;
            $a[$kind==='release'?'released_cents':($kind==='liquidation'?'liquidated_cents':'returned_cents')]+=$kind==='release'?$debit:$credit;$a['operations'][]=$o;if($kind==='release')$a['release_count']++;}
        unset($a);
    }
    $s=$pdo->prepare("SELECT l.id,l.account_id,l.debit_amount,l.credit_amount FROM journal_entry_lines l JOIN journal_entries j ON j.id=l.journal_entry_id JOIN advance_control_designations d ON d.account_id=l.account_id WHERE j.status='posted' AND j.entry_date<=? ORDER BY l.id");$s->execute([$asof]);
    foreach($s->fetchAll() as $l){$account=(int)$l['account_id'];$reconciliation[$account]['ledger_cents']+=ledger_cents($l['debit_amount'])-ledger_cents($l['credit_amount']);if(!($linked[(int)$l['id']]??false))$reconciliation[$account]['errors'][]='Unlinked or invalid control line #'.$l['id'];}
    $s=$pdo->prepare('SELECT * FROM cash_advance_due_changes WHERE effective_date<=? ORDER BY effective_date,id');$s->execute([$asof]);foreach($s->fetchAll() as $e)$advances[(int)$e['advance_id']]['due_date']=$e['new_due_date'];
    foreach($advances as $id=>&$a){if($a['release_date']>$asof){unset($advances[$id]);continue;}$a['outstanding_cents']=$a['released_cents']-$a['liquidated_cents']-$a['returned_cents'];$account=(int)$a['control_account_id'];$reconciliation[$account]['register_cents']+=$a['outstanding_cents'];if($a['release_count']!==1||$a['outstanding_cents']<0)$reconciliation[$account]['errors'][]='Invalid release or balance for '.advance_number($id);
        $a['status']=$a['outstanding_cents']===0?'settled':($a['liquidated_cents']+$a['returned_cents']>0?'partially_settled':'outstanding');
        $a['overdue_days']=$a['outstanding_cents']>0&&$asof>$a['due_date']?(int)(new DateTimeImmutable($a['due_date'],new DateTimeZone('Asia/Manila')))->diff(new DateTimeImmutable($asof,new DateTimeZone('Asia/Manila')))->days:0;
        $days=$a['overdue_days'];$a['aging_bucket']=$days===0?'Not overdue':($days<=30?'1–30':($days<=60?'31–60':($days<=90?'61–90':'>90')));}
    unset($a);
    foreach($reconciliation as &$r){$r['difference']=ledger_decimal($r['ledger_cents']-$r['register_cents']);$r['ledger_balance']=ledger_decimal($r['ledger_cents']);$r['register_balance']=ledger_decimal($r['register_cents']);$r['ok']=$r['ledger_cents']===$r['register_cents']&&!$r['errors'];unset($r['ledger_cents'],$r['register_cents']);}unset($r);
    return ['advances'=>$advances,'reconciliation'=>array_values($reconciliation)];
}
function advance_reconciled(array $state,?int $account=null): void {foreach($state['reconciliation'] as $r)if(($account===null||$r['account_id']===$account)&&!$r['ok'])throw new JournalProblem('Advance control reconciliation failed for '.$r['account_name'].'. Resolve linked-line integrity before posting.',409);}
function advance_proof_context(PDO $pdo,array $d,array $p): array
{
    if($d['workflow_kind']!=='advance_return')throw new JournalProblem('Return proof confirmation applies only to cash returns.');
    $docs=workspace_canonical_documents($p['documents']);if(!$docs)throw new JournalProblem('Attach and review at least one return proof image.');$proof=[];
    foreach($docs as $doc){if($doc['purpose']!=='supporting')throw new JournalProblem('Return proof is informational, without expenditure allocations.');$r=receipt_owned($pdo,(int)$doc['receipt_id'],(int)$d['owner_id']);receipt_file_verify($r);$proof[]=$doc+['sha256'=>$r['File_SHA256']];}
    $amount=journal_amount($p['cash_amount']);if($amount<=0)throw new JournalProblem('Enter a positive return amount.');
    return ['draft_id'=>(int)$d['id'],'workflow_kind'=>$d['workflow_kind'],'advance_id'=>(int)$d['advance_id'],'amount'=>ledger_decimal($amount),'cash_account_id'=>journal_id($p['cash_account_id']),'entry_date'=>advance_date($p['entry_date']),'proof'=>$proof];
}
function advance_confirm(PDO $pdo,int $uid,array $r): array
{
    advance_guard($pdo,$uid,$r,true);$id=journal_id(journal_string($r,'draft_id'));
    return workspace_tx($pdo,$uid,function()use($pdo,$uid,$id,$r){$d=workspace_draft($pdo,$uid,$id,true);advance_draft($d);workspace_revision($d,$r);advance_load($pdo,(int)$d['advance_id'],true);
        $context=advance_proof_context($pdo,$d,$d['payload']);$input=advance_canonical($pdo,$d,$d['payload']);workspace_resources($pdo,$uid,$d,$input,advance_load($pdo,(int)$d['advance_id']));
        $confirmation=['context'=>$context,'fingerprint'=>hash('sha256',workspace_json($context)),'confirmed_by'=>$uid,'confirmed_at'=>gmdate('Y-m-d H:i:s')];
        $pdo->prepare('UPDATE journal_drafts SET return_confirmation=?,revision=revision+1,updated_at=UTC_TIMESTAMP() WHERE id=?')->execute([workspace_json($confirmation),$id]);
        workspace_audit($pdo,$uid,AUDIT_ACTION_EDIT,'Advance Return Proof',$id,null,$confirmation);return workspace_draft_public(workspace_draft($pdo,$uid,$id));});
}
function advance_prepare(PDO $pdo,int $uid,array $d,array $input,string $version,?array $original): array
{
    advance_date($input['entry_date']);$ctx=$input['advance_context'];$kind=$d['workflow_kind'];
    if($kind==='advance_release'){if($ctx['due_date']<$input['entry_date'])throw new JournalProblem('Liquidation due date cannot precede release.');if($ctx['approval']!==null&&$ctx['approval']['date']>$input['entry_date'])throw new JournalProblem('Approval date cannot follow release.');}
    elseif($input['entry_date']<$original['release_date'])throw new JournalProblem('Settlement date cannot precede release.');
    $resources=workspace_resources($pdo,$uid,$d,$input,$original);extract($resources);$control=$ctx['control_account_id'];
    $designations=array_map('intval',$pdo->query('SELECT account_id FROM advance_control_designations')->fetchAll(PDO::FETCH_COLUMN));
    $a=$accounts[$control];if(!in_array($control,$designations,true)||$a['Account_Type']!=='Asset'||$a['Normal_Balance']!=='Debit'||(int)$a['Is_Cash_Account']!==0)throw new JournalProblem('Select an active, designated Debit-normal noncash Asset control account.');
    if($kind==='advance_release'&&$party['party_type']!=='person')throw new JournalProblem('The accountable employee must be an active person-type party.');
    $claims=[];$eligible=0;$covered=0;$allocated=[];
    foreach($input['lines'] as $l){$a=$accounts[$l['account_id']];if($l['client_id']==='control')continue;if(in_array((int)$l['account_id'],$designations,true))throw new JournalProblem('Only the generated original control line may use a designated advance account.');
        if($kind!=='advance_liquidation'){if((int)$a['Is_Cash_Account']!==1)throw new JournalProblem('Select an active cash/bank account.');continue;}
        if((int)$a['Is_Cash_Account']!==0)throw new JournalProblem('Liquidation cannot move cash.');
        if(journal_amount($l['debit_amount'])>0){if(!in_array($a['Account_Type'],['Expense','Asset'],true)||$a['Normal_Balance']!=='Debit')throw new JournalProblem('Liquidation debits must be expenses or Debit-normal noncash assets.');$claims[$l['client_id']]=$l;$eligible+=journal_amount($l['debit_amount']);}
        elseif($a['Account_Type']!=='Liability'||$a['Normal_Balance']!=='Credit'||($ctx['line_notes'][$l['client_id']]??'')==='')throw new JournalProblem('Liability credits require a Credit-normal Liability account and an explanatory allocation note.');
    }
    foreach($input['documents'] as $doc){if($kind!=='advance_liquidation'){if($doc['purpose']!=='supporting')throw new JournalProblem('Release and return documents are informational supporting proof.');continue;}
        if($doc['purpose']!=='amount')continue;if($doc['support_side']!=='debit')throw new JournalProblem('Liquidation evidence supports expenditure/asset debits only.');
        foreach($doc['allocations'] as $al){if(!isset($claims[$al['client_id']]))throw new JournalProblem('Evidence cannot support liability or control credits.');$c=journal_amount($al['amount']);$allocated[$al['client_id']]=($allocated[$al['client_id']]??0)+$c;if($allocated[$al['client_id']]>journal_amount($claims[$al['client_id']]['debit_amount']))throw new JournalProblem('Combined evidence exceeds this cost line.');$covered+=$c;}}
    if($kind==='advance_liquidation')foreach($claims as $id=>$l)if(($allocated[$id]??0)!==journal_amount($l['debit_amount']))throw new JournalProblem('Fully cover every expenditure/asset debit with reviewed monetary evidence. Unsupported claims remain unposted drafts.');
    if($kind==='advance_return'){$context=advance_proof_context($pdo,$d,$d['payload']);$confirmation=$input['return_confirmation'];if(!$confirmation||!hash_equals($confirmation['fingerprint'],hash('sha256',workspace_json($context)))||$confirmation['context']!==$context)throw new JournalProblem('Confirm the proof for this advance, amount and return context before review.',409);}
    $state=advance_state($pdo,journal_today());advance_reconciled($state,$control);$remaining=null;
    if($original!==null){$remaining=$state['advances'][(int)$original['id']]['outstanding_cents']??0;if(journal_amount($ctx['reduction'])>$remaining)throw new JournalProblem('Settlement exceeds the current outstanding PHP '.ledger_decimal($remaining).'. Save a revised claim; no financial entry was posted.',409);}
    $coverage=['status'=>$kind==='advance_liquidation'?'Fully covered':($kind==='advance_return'?'Return proof confirmed':($input['documents']?'Supporting proof reviewed':'Optional proof not supplied')),'debit'=>['eligible'=>ledger_decimal($eligible),'covered'=>ledger_decimal($covered)],'credit'=>['eligible'=>'0.00','covered'=>'0.00']];
    $evidence=array_map(fn($r)=>[$r['ReceiptID'],$r['File_SHA256'],$r['attempt_version']],$receipts);
    return $resources+['input'=>$input,'coverage'=>$coverage,'remaining'=>$remaining,'fingerprint'=>hash('sha256',workspace_json([$version,$d['revision'],$input,$party,$projects,$accounts,$evidence,$original['revision']??null,$remaining]))];
}
function advance_review(PDO $pdo,int $uid,array $r): array
{
    advance_guard($pdo,$uid,$r,true);$id=journal_id(journal_string($r,'draft_id'));
    return workspace_tx($pdo,$uid,function($version)use($pdo,$uid,$r,$id){$d=workspace_draft($pdo,$uid,$id,true);advance_draft($d);workspace_revision($d,$r);$original=$d['workflow_kind']==='advance_release'?null:advance_load($pdo,(int)$d['advance_id'],true);$input=advance_canonical($pdo,$d,$d['payload'],$original);$prepared=advance_prepare($pdo,$uid,$d,$input,$version,$original);$lines=[];
        foreach($input['lines'] as $l)$lines[]=$l+['account_name'=>$prepared['accounts'][$l['account_id']]['Name'],'project_name'=>$l['fund_project_id']===null?'Organization operations':$prepared['projects'][$l['fund_project_id']]['name']];
        return ['input'=>$input,'lines'=>$lines,'party'=>$prepared['party'],'coverage'=>$prepared['coverage'],'outstanding'=>$prepared['remaining']===null?null:ledger_decimal($prepared['remaining']),'token'=>workspace_token($d,$prepared['fingerprint'],time()+900)];});
}
function advance_post(PDO $pdo,int $uid,array $r): array
{
    advance_guard($pdo,$uid,$r,true);$id=journal_id(journal_string($r,'draft_id'));$key=journal_string($r,'submission_key');
    return workspace_tx($pdo,$uid,function($version)use($pdo,$uid,$r,$id,$key){$d=workspace_draft($pdo,$uid,$id,true);advance_draft($d);if(!hash_equals($d['submission_key'],$key))throw new JournalProblem('Draft submission key does not match.',409);
        $original=$d['workflow_kind']==='advance_release'?null:advance_load($pdo,(int)$d['advance_id'],true);$input=advance_canonical($pdo,$d,$r['payload']??[],$original);$hash=hash('sha256',workspace_json($input));
        if($d['state']==='Posted'){$result=journal_existing($pdo,$key,$uid,$hash);if(!$result||(int)$result['id']!==(int)$d['posted_journal_id'])throw new JournalProblem('Posted advance draft is inconsistent.',409);return $result+['advance_id'=>(int)$d['advance_id']];}
        workspace_revision($d,$r);if(workspace_json($input)!==workspace_json(advance_canonical($pdo,$d,$d['payload'],$original)))throw new JournalProblem('Save and review the latest changes before posting.',409);
        $prepared=advance_prepare($pdo,$uid,$d,$input,$version,$original);$token=journal_string($r,'review_token');
        if(!preg_match('/\A([0-9]{10})\.([a-f0-9]{64})\z/',$token,$m)||!isset($_SESSION['workspace_review_secret'])||time()>(int)$m[1]||!hash_equals(workspace_token($d,$prepared['fingerprint'],(int)$m[1]),$token))throw new JournalProblem('Review expired or accounting data changed. Review again.',409);
        $written=workspace_write_post($pdo,$uid,$d,$input,$prepared);$advanceId=$original===null?null:(int)$original['id'];$ctx=$input['advance_context'];
        if($advanceId===null){$s=$pdo->prepare('INSERT INTO cash_advances(party_id,originating_project_id,control_account_id,release_journal_id,purpose,reference,party_snapshot,project_snapshot,initial_due_date,approval_snapshot,created_by,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,UTC_TIMESTAMP())');
            $s->execute([$input['party_id'],$ctx['originating_project_id'],$ctx['control_account_id'],$written['id'],$input['description'],$input['reference']??'',workspace_json($prepared['party']),$ctx['originating_project_id']===null?null:workspace_json($prepared['projects'][$ctx['originating_project_id']]),$ctx['due_date'],$ctx['approval']===null?null:workspace_json($ctx['approval']),$uid]);$advanceId=(int)$pdo->lastInsertId();$pdo->prepare('UPDATE journal_drafts SET advance_id=? WHERE id=?')->execute([$advanceId,$id]);}
        else $pdo->prepare('UPDATE cash_advances SET revision=revision+1 WHERE id=?')->execute([$advanceId]);
        $snapshot=['input'=>$input,'coverage'=>$prepared['coverage'],'return_confirmation'=>$input['return_confirmation']];
        $pdo->prepare('INSERT INTO cash_advance_operations(advance_id,operation_kind,journal_id,draft_id,control_line_id,review_snapshot,created_by,created_at) VALUES(?,?,?,?,?,?,?,UTC_TIMESTAMP())')->execute([$advanceId,substr($d['workflow_kind'],8),$written['id'],$id,$written['line_ids']['control'],workspace_json($snapshot),$uid]);
        workspace_audit($pdo,$uid,AUDIT_ACTION_CREATE,'Cash Advance Operation',$advanceId,null,$snapshot+['journal_id'=>$written['id'],'number'=>advance_number($advanceId)]);
        return ['id'=>$written['id'],'duplicate'=>false,'advance_id'=>$advanceId];});
}
function advance_extend_due(PDO $pdo,int $uid,array $r): array
{
    advance_guard($pdo,$uid,$r,true);$id=journal_id(journal_string($r,'advance_id'));$new=advance_date(journal_string($r,'due_date'),true);$reason=journal_string($r,'reason');if($reason===''||mb_strlen($reason)>2000)throw new JournalProblem('Enter an extension reason of at most 2,000 characters.');
    return workspace_tx($pdo,$uid,function()use($pdo,$uid,$r,$id,$new,$reason){$a=advance_load($pdo,$id,true);if((string)$a['revision']!==journal_string($r,'revision'))throw new JournalProblem('Advance changed. Refresh before extending.',409);$state=advance_state($pdo,journal_today());advance_reconciled($state,(int)$a['control_account_id']);$current=$state['advances'][$id];
        if($current['outstanding_cents']<=0||$new<journal_today()||$new<=$current['due_date'])throw new JournalProblem('Extend an outstanding advance to a later deadline, on or after today.');
        $pdo->prepare('INSERT INTO cash_advance_due_changes(advance_id,old_due_date,new_due_date,effective_date,reason,created_by,created_at) VALUES(?,?,?,?,?,?,UTC_TIMESTAMP())')->execute([$id,$current['due_date'],$new,journal_today(),$reason,$uid]);$pdo->prepare('UPDATE cash_advances SET revision=revision+1 WHERE id=?')->execute([$id]);
        workspace_audit($pdo,$uid,AUDIT_ACTION_EDIT,'Cash Advance Deadline',$id,['due_date'=>$current['due_date']],['due_date'=>$new,'effective_date'=>journal_today(),'reason'=>$reason]);stage1_write_changed($pdo);return ['saved'=>true];});
}
function advance_summary(array $a): array
{
    $party=json_decode($a['party_snapshot'],true,32,JSON_THROW_ON_ERROR);$project=$a['project_snapshot']===null?null:json_decode($a['project_snapshot'],true,32,JSON_THROW_ON_ERROR);
    return ['id'=>(int)$a['id'],'number'=>advance_number((int)$a['id']),'revision'=>(int)$a['revision'],'party_id'=>(int)$a['party_id'],'employee'=>$party['name'],'employee_code'=>$party['code'],'originating_project_id'=>$a['originating_project_id']===null?null:(int)$a['originating_project_id'],'project'=>$project['name']??'Organization operations','project_code'=>$project['code']??'','control_account_id'=>(int)$a['control_account_id'],'purpose'=>$a['purpose'],'reference'=>$a['reference'],'release_date'=>$a['release_date'],'due_date'=>$a['due_date'],'initial_due_date'=>$a['initial_due_date'],'released'=>ledger_decimal($a['released_cents']),'liquidated'=>ledger_decimal($a['liquidated_cents']),'returned'=>ledger_decimal($a['returned_cents']),'outstanding'=>ledger_decimal($a['outstanding_cents']),'status'=>$a['status'],'overdue'=>$a['overdue_days']>0,'overdue_days'=>$a['overdue_days'],'aging_bucket'=>$a['aging_bucket']];
}
function advance_register(PDO $pdo,int $uid,array $r): array
{
    advance_guard($pdo,$uid);$asof=advance_date(journal_string($r,'as_of',true)?:journal_today());$person=journal_id(journal_string($r,'party_id',true),true);$project=journal_string($r,'project_id',true);$control=journal_id(journal_string($r,'control_account_id',true),true);$status=journal_string($r,'status',true);$overdue=journal_string($r,'overdue',true);$search=journal_string($r,'search',true);$page=journal_string($r,'page',true)?:'1';
    if($project!==''&&$project!=='organization')journal_id($project);if(!in_array($status,['','outstanding','partially_settled','settled'],true)||!in_array($overdue,['','0','1'],true)||!preg_match('/\A[1-9][0-9]{0,8}\z/',$page)||mb_strlen($search)>200)throw new JournalProblem('Invalid register filter.');
    return accounting_read($pdo,function()use($pdo,$asof,$person,$project,$control,$status,$overdue,$search,$page){$state=advance_state($pdo,$asof);$items=[];$totals=['released'=>0,'liquidated'=>0,'returned'=>0,'outstanding'=>0];$terms=preg_split('/\s+/u',mb_strtolower(trim($search)),-1,PREG_SPLIT_NO_EMPTY);
        foreach($state['advances'] as $a){$item=advance_summary($a);if(($person!==null&&$item['party_id']!==$person)||($control!==null&&$item['control_account_id']!==$control)||($project==='organization'&&$item['originating_project_id']!==null)||($project!==''&&$project!=='organization'&&$item['originating_project_id']!==(int)$project)||($status!==''&&$item['status']!==$status)||($overdue!==''&&$item['overdue']!==($overdue==='1')))continue;$text=mb_strtolower(implode(' ',[$item['number'],$item['employee'],$item['employee_code'],$item['purpose'],$item['reference']]));foreach($terms as $term)if(!str_contains($text,$term))continue 2;
            $items[]=$item;foreach($totals as $k=>$_)$totals[$k]+=ledger_cents($item[$k]);}
        usort($items,fn($a,$b)=>strcmp($b['release_date'],$a['release_date'])?:($b['id']<=>$a['id']));$count=count($items);$pages=max(1,(int)ceil($count/25));$current=min((int)$page,$pages);return ['as_of'=>$asof,'rows'=>array_slice($items,($current-1)*25,25),'count'=>$count,'page'=>$current,'pages'=>$pages,'totals'=>array_map('ledger_decimal',$totals),'reconciliation'=>$state['reconciliation'],'restatement_notice'=>'Historical balances include all currently recorded postings through the selected accounting date.'];});
}
function advance_detail(PDO $pdo,int $uid,int $id,string $asof): array
{
    $role=advance_guard($pdo,$uid);$asof=advance_date($asof?:journal_today());
    return accounting_read($pdo,function()use($pdo,$id,$asof,$role){$state=advance_state($pdo,$asof);if(!isset($state['advances'][$id]))throw new JournalProblem('Advance is not available at this reporting date.',404);$a=$state['advances'][$id];$out=advance_summary($a);$out['as_of']=$asof;$out['operations']=[];
        foreach($a['operations'] as $o){$snapshot=json_decode($o['review_snapshot'],true,64,JSON_THROW_ON_ERROR);$s=$pdo->prepare('SELECT l.*,c.Name account_name FROM journal_entry_lines l JOIN Categories c ON c.CategoryID=l.account_id WHERE journal_entry_id=? ORDER BY l.id');$s->execute([$o['journal_id']]);$lines=$s->fetchAll();
            $op=['kind'=>$o['operation_kind'],'journal_id'=>(int)$o['journal_id'],'date'=>$o['entry_date'],'amount'=>$o['operation_kind']==='release'?$o['debit_amount']:$o['credit_amount'],'coverage'=>$snapshot['coverage'],'lines'=>$lines,'reference'=>$snapshot['input']['reference'],'recorded_at_display'=>(new DateTimeImmutable($o['created_at'],new DateTimeZone('UTC')))->setTimezone(new DateTimeZone('Asia/Manila'))->format('Y-m-d H:i:s')];
            if($role==='Admin'){$op['attachments']=receipt_journal_metadata($pdo,[(int)$o['journal_id']],$role)[(int)$o['journal_id']]??[];$op['private_review']=$snapshot;}$out['operations'][]=$op;}
        $s=$pdo->prepare('SELECT id,old_due_date,new_due_date,effective_date,reason,created_at FROM cash_advance_due_changes WHERE advance_id=? AND effective_date<=? ORDER BY effective_date,id');$s->execute([$id,$asof]);$out['due_changes']=$s->fetchAll();if($role==='Admin'){$out['external_approval']=$a['approval_snapshot']===null?null:json_decode($a['approval_snapshot'],true,32,JSON_THROW_ON_ERROR);$out['original_party']=json_decode($a['party_snapshot'],true);$out['original_project']=$a['project_snapshot']===null?null:json_decode($a['project_snapshot'],true);}
        $out['can_settle']=$role==='Admin'&&$asof===journal_today()&&$a['outstanding_cents']>0;$out['reconciliation']=$state['reconciliation'];return $out;});
}
function advance_draft_public(PDO $pdo,int $uid,int $id): array
{
    $d=workspace_draft($pdo,$uid,$id);advance_draft($d);$out=workspace_draft_public($d);$out['document_details']=[];
    foreach($d['payload']['documents'] as $doc){$r=receipt_owned($pdo,(int)$doc['receipt_id'],$uid);$out['document_details'][]=['id'=>(int)$r['ReceiptID'],'name'=>$r['Original_Filename']?:'Supporting image'];}
    if($d['state']==='Posted'){$s=$pdo->prepare('SELECT party_snapshot FROM journal_entries WHERE id=?');$s->execute([$d['posted_journal_id']]);$out['posted_party']=json_decode($s->fetchColumn(),true);$s=$pdo->prepare('SELECT l.account_id,c.Name account_name,c.Account_Code account_code,l.fund_project_id,l.project_code_snapshot,l.project_name_snapshot FROM journal_entry_lines l JOIN Categories c ON c.CategoryID=l.account_id WHERE l.journal_entry_id=? ORDER BY l.id');$s->execute([$d['posted_journal_id']]);$out['posted_lines']=$s->fetchAll();}
    return $out;
}
